#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("x_in", 1200, hls_in, 0, "ap_vld", "in_data", 1),
	Port_Property("layer2_out_0", 25, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("layer2_out_1", 25, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("layer2_out_2", 25, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("layer2_out_3", 25, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("layer2_out_4", 25, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("layer2_out_5", 25, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("layer2_out_6", 25, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("layer2_out_7", 25, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("layer2_out_8", 25, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("layer2_out_9", 25, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("x_in_ap_vld", 1, hls_in, 0, "ap_vld", "in_vld", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("layer2_out_0_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("layer2_out_1_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("layer2_out_2_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("layer2_out_3_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("layer2_out_4_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("layer2_out_5_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("layer2_out_6_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("layer2_out_7_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("layer2_out_8_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("layer2_out_9_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "model_test";
