Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    act_agg:
      Precision:
        result: fixed<20,11,RND_CONV,SAT,0>
      Trace: false
    agg:
      Precision:
        result: auto
      Trace: false
    phi1:
      Precision:
        bias: fixed<8,1,TRN,WRAP,0>
        result: auto
        weight: fixed<8,1,TRN,WRAP,0>
      Trace: false
    phi1_linear:
      Precision:
        result: auto
      Trace: false
    phi2:
      Precision:
        bias: fixed<8,1,TRN,WRAP,0>
        result: auto
        weight: fixed<8,1,TRN,WRAP,0>
      Trace: false
    phi2_linear:
      Precision:
        result: auto
      Trace: false
    phi3:
      Precision:
        bias: fixed<8,1,TRN,WRAP,0>
        result: auto
        weight: fixed<8,1,TRN,WRAP,0>
      Trace: false
    phi3_linear:
      Precision:
        result: auto
      Trace: false
    phi_input:
      Precision: ap_fixed<12, 4, AP_RND, AP_SAT>
      Trace: false
    relu1:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT,0>
      Trace: false
    relu2:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT,0>
      Trace: false
    relu3:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT,0>
      Trace: false
    relu4:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT,0>
      Trace: false
    rho1:
      Precision:
        bias: fixed<8,1,TRN,WRAP,0>
        result: auto
        weight: fixed<8,1,TRN,WRAP,0>
      Trace: false
    rho1_linear:
      Precision:
        result: auto
      Trace: false
    rho2:
      Precision:
        bias: fixed<8,1,TRN,WRAP,0>
        result: auto
        weight: fixed<8,1,TRN,WRAP,0>
      Trace: false
    rho2_linear:
      Precision:
        result: auto
      Trace: false
    softmax:
      Precision:
        result: auto
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_test/keras_model.keras'
OutputDir: model_test
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: model_test
Stamp: ba31644d
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
