// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_ST_fsm_state1 = "1";
const sc_lv<4> dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_ST_fsm_state2 = "10";
const sc_lv<4> dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_ST_fsm_state3 = "100";
const sc_lv<4> dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_ST_fsm_state4 = "1000";
const sc_lv<32> dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_const_lv32_3 = "11";
const sc_lv<32> dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_const_lv32_2 = "10";
const sc_lv<32> dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_const_lv32_1 = "1";
const bool dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::ap_const_boolean_1 = true;

dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627 = new dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s("grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627");
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->ap_clk(ap_clk);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->ap_rst(ap_rst);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_0_V_read(data_0_V_reg_811);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_1_V_read(data_1_V_reg_816);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_2_V_read(data_2_V_reg_821);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_3_V_read(data_3_V_reg_826);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_4_V_read(data_4_V_reg_831);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_5_V_read(data_5_V_reg_836);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_6_V_read(data_6_V_reg_841);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_7_V_read(data_7_V_reg_846);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_8_V_read(data_8_V_reg_851);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_9_V_read(data_9_V_reg_856);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_10_V_read(data_10_V_reg_861);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_11_V_read(data_11_V_reg_866);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_12_V_read(data_12_V_reg_871);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_13_V_read(data_13_V_reg_876);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_14_V_read(data_14_V_reg_881);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_15_V_read(data_15_V_reg_886);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_16_V_read(data_16_V_reg_891);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_17_V_read(data_17_V_reg_896);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_18_V_read(data_18_V_reg_901);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_19_V_read(data_19_V_reg_906);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_20_V_read(data_20_V_reg_911);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_21_V_read(data_21_V_reg_916);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_22_V_read(data_22_V_reg_921);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_23_V_read(data_23_V_reg_926);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_24_V_read(data_24_V_reg_931);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_25_V_read(data_25_V_reg_936);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_26_V_read(data_26_V_reg_941);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_27_V_read(data_27_V_reg_946);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_28_V_read(data_28_V_reg_951);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_29_V_read(data_29_V_reg_956);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_30_V_read(data_30_V_reg_961);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->data_31_V_read(data_31_V_reg_966);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->ap_return_0(grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_0);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->ap_return_1(grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_1);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->ap_return_2(grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_2);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->ap_return_3(grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_3);
    grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627->ap_return_4(grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_4);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_data_stream_V_data_0_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_0_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_0_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_10_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_10_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_10_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_11_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_11_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_11_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_12_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_12_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_12_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_13_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_13_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_13_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_14_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_14_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_14_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_15_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_15_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_15_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_16_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_16_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_16_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_17_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_17_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_17_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_18_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_18_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_18_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_19_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_19_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_19_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_1_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_1_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_1_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_20_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_20_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_20_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_21_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_21_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_21_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_22_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_22_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_22_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_23_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_23_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_23_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_24_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_24_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_24_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_25_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_25_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_25_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_26_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_26_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_26_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_27_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_27_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_27_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_28_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_28_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_28_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_29_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_29_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_29_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_2_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_2_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_2_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_30_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_30_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_30_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_31_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_31_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_31_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_3_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_3_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_3_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_4_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_4_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_4_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_5_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_5_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_5_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_6_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_6_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_6_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_7_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_7_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_7_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_8_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_8_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_8_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_data_stream_V_data_9_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_stream_V_data_9_V_empty_n );

    SC_METHOD(thread_data_stream_V_data_9_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op5 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_io_acc_block_signal_op5);
    sensitive << ( data_stream_V_data_0_V_empty_n );
    sensitive << ( data_stream_V_data_1_V_empty_n );
    sensitive << ( data_stream_V_data_2_V_empty_n );
    sensitive << ( data_stream_V_data_3_V_empty_n );
    sensitive << ( data_stream_V_data_4_V_empty_n );
    sensitive << ( data_stream_V_data_5_V_empty_n );
    sensitive << ( data_stream_V_data_6_V_empty_n );
    sensitive << ( data_stream_V_data_7_V_empty_n );
    sensitive << ( data_stream_V_data_8_V_empty_n );
    sensitive << ( data_stream_V_data_9_V_empty_n );
    sensitive << ( data_stream_V_data_10_V_empty_n );
    sensitive << ( data_stream_V_data_11_V_empty_n );
    sensitive << ( data_stream_V_data_12_V_empty_n );
    sensitive << ( data_stream_V_data_13_V_empty_n );
    sensitive << ( data_stream_V_data_14_V_empty_n );
    sensitive << ( data_stream_V_data_15_V_empty_n );
    sensitive << ( data_stream_V_data_16_V_empty_n );
    sensitive << ( data_stream_V_data_17_V_empty_n );
    sensitive << ( data_stream_V_data_18_V_empty_n );
    sensitive << ( data_stream_V_data_19_V_empty_n );
    sensitive << ( data_stream_V_data_20_V_empty_n );
    sensitive << ( data_stream_V_data_21_V_empty_n );
    sensitive << ( data_stream_V_data_22_V_empty_n );
    sensitive << ( data_stream_V_data_23_V_empty_n );
    sensitive << ( data_stream_V_data_24_V_empty_n );
    sensitive << ( data_stream_V_data_25_V_empty_n );
    sensitive << ( data_stream_V_data_26_V_empty_n );
    sensitive << ( data_stream_V_data_27_V_empty_n );
    sensitive << ( data_stream_V_data_28_V_empty_n );
    sensitive << ( data_stream_V_data_29_V_empty_n );
    sensitive << ( data_stream_V_data_30_V_empty_n );
    sensitive << ( data_stream_V_data_31_V_empty_n );

    SC_METHOD(thread_io_acc_block_signal_op84);
    sensitive << ( res_stream_V_data_0_V_full_n );
    sensitive << ( res_stream_V_data_1_V_full_n );
    sensitive << ( res_stream_V_data_2_V_full_n );
    sensitive << ( res_stream_V_data_3_V_full_n );
    sensitive << ( res_stream_V_data_4_V_full_n );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_stream_V_data_0_V_blk_n);
    sensitive << ( res_stream_V_data_0_V_full_n );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_res_stream_V_data_0_V_din);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_data_0_V_reg_971 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_res_stream_V_data_0_V_write);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_res_stream_V_data_1_V_blk_n);
    sensitive << ( res_stream_V_data_1_V_full_n );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_res_stream_V_data_1_V_din);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_data_1_V_reg_976 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_res_stream_V_data_1_V_write);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_res_stream_V_data_2_V_blk_n);
    sensitive << ( res_stream_V_data_2_V_full_n );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_res_stream_V_data_2_V_din);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_data_2_V_reg_981 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_res_stream_V_data_2_V_write);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_res_stream_V_data_3_V_blk_n);
    sensitive << ( res_stream_V_data_3_V_full_n );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_res_stream_V_data_3_V_din);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_data_3_V_reg_986 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_res_stream_V_data_3_V_write);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_res_stream_V_data_4_V_blk_n);
    sensitive << ( res_stream_V_data_4_V_full_n );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_res_stream_V_data_4_V_din);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_data_4_V_reg_991 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_res_stream_V_data_4_V_write);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( io_acc_block_signal_op84 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( io_acc_block_signal_op5 );
    sensitive << ( io_acc_block_signal_op84 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, data_stream_V_data_0_V_dout, "(port)data_stream_V_data_0_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_0_V_empty_n, "(port)data_stream_V_data_0_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_0_V_read, "(port)data_stream_V_data_0_V_read");
    sc_trace(mVcdFile, data_stream_V_data_1_V_dout, "(port)data_stream_V_data_1_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_1_V_empty_n, "(port)data_stream_V_data_1_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_1_V_read, "(port)data_stream_V_data_1_V_read");
    sc_trace(mVcdFile, data_stream_V_data_2_V_dout, "(port)data_stream_V_data_2_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_2_V_empty_n, "(port)data_stream_V_data_2_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_2_V_read, "(port)data_stream_V_data_2_V_read");
    sc_trace(mVcdFile, data_stream_V_data_3_V_dout, "(port)data_stream_V_data_3_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_3_V_empty_n, "(port)data_stream_V_data_3_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_3_V_read, "(port)data_stream_V_data_3_V_read");
    sc_trace(mVcdFile, data_stream_V_data_4_V_dout, "(port)data_stream_V_data_4_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_4_V_empty_n, "(port)data_stream_V_data_4_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_4_V_read, "(port)data_stream_V_data_4_V_read");
    sc_trace(mVcdFile, data_stream_V_data_5_V_dout, "(port)data_stream_V_data_5_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_5_V_empty_n, "(port)data_stream_V_data_5_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_5_V_read, "(port)data_stream_V_data_5_V_read");
    sc_trace(mVcdFile, data_stream_V_data_6_V_dout, "(port)data_stream_V_data_6_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_6_V_empty_n, "(port)data_stream_V_data_6_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_6_V_read, "(port)data_stream_V_data_6_V_read");
    sc_trace(mVcdFile, data_stream_V_data_7_V_dout, "(port)data_stream_V_data_7_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_7_V_empty_n, "(port)data_stream_V_data_7_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_7_V_read, "(port)data_stream_V_data_7_V_read");
    sc_trace(mVcdFile, data_stream_V_data_8_V_dout, "(port)data_stream_V_data_8_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_8_V_empty_n, "(port)data_stream_V_data_8_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_8_V_read, "(port)data_stream_V_data_8_V_read");
    sc_trace(mVcdFile, data_stream_V_data_9_V_dout, "(port)data_stream_V_data_9_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_9_V_empty_n, "(port)data_stream_V_data_9_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_9_V_read, "(port)data_stream_V_data_9_V_read");
    sc_trace(mVcdFile, data_stream_V_data_10_V_dout, "(port)data_stream_V_data_10_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_10_V_empty_n, "(port)data_stream_V_data_10_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_10_V_read, "(port)data_stream_V_data_10_V_read");
    sc_trace(mVcdFile, data_stream_V_data_11_V_dout, "(port)data_stream_V_data_11_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_11_V_empty_n, "(port)data_stream_V_data_11_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_11_V_read, "(port)data_stream_V_data_11_V_read");
    sc_trace(mVcdFile, data_stream_V_data_12_V_dout, "(port)data_stream_V_data_12_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_12_V_empty_n, "(port)data_stream_V_data_12_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_12_V_read, "(port)data_stream_V_data_12_V_read");
    sc_trace(mVcdFile, data_stream_V_data_13_V_dout, "(port)data_stream_V_data_13_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_13_V_empty_n, "(port)data_stream_V_data_13_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_13_V_read, "(port)data_stream_V_data_13_V_read");
    sc_trace(mVcdFile, data_stream_V_data_14_V_dout, "(port)data_stream_V_data_14_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_14_V_empty_n, "(port)data_stream_V_data_14_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_14_V_read, "(port)data_stream_V_data_14_V_read");
    sc_trace(mVcdFile, data_stream_V_data_15_V_dout, "(port)data_stream_V_data_15_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_15_V_empty_n, "(port)data_stream_V_data_15_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_15_V_read, "(port)data_stream_V_data_15_V_read");
    sc_trace(mVcdFile, data_stream_V_data_16_V_dout, "(port)data_stream_V_data_16_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_16_V_empty_n, "(port)data_stream_V_data_16_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_16_V_read, "(port)data_stream_V_data_16_V_read");
    sc_trace(mVcdFile, data_stream_V_data_17_V_dout, "(port)data_stream_V_data_17_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_17_V_empty_n, "(port)data_stream_V_data_17_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_17_V_read, "(port)data_stream_V_data_17_V_read");
    sc_trace(mVcdFile, data_stream_V_data_18_V_dout, "(port)data_stream_V_data_18_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_18_V_empty_n, "(port)data_stream_V_data_18_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_18_V_read, "(port)data_stream_V_data_18_V_read");
    sc_trace(mVcdFile, data_stream_V_data_19_V_dout, "(port)data_stream_V_data_19_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_19_V_empty_n, "(port)data_stream_V_data_19_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_19_V_read, "(port)data_stream_V_data_19_V_read");
    sc_trace(mVcdFile, data_stream_V_data_20_V_dout, "(port)data_stream_V_data_20_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_20_V_empty_n, "(port)data_stream_V_data_20_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_20_V_read, "(port)data_stream_V_data_20_V_read");
    sc_trace(mVcdFile, data_stream_V_data_21_V_dout, "(port)data_stream_V_data_21_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_21_V_empty_n, "(port)data_stream_V_data_21_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_21_V_read, "(port)data_stream_V_data_21_V_read");
    sc_trace(mVcdFile, data_stream_V_data_22_V_dout, "(port)data_stream_V_data_22_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_22_V_empty_n, "(port)data_stream_V_data_22_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_22_V_read, "(port)data_stream_V_data_22_V_read");
    sc_trace(mVcdFile, data_stream_V_data_23_V_dout, "(port)data_stream_V_data_23_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_23_V_empty_n, "(port)data_stream_V_data_23_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_23_V_read, "(port)data_stream_V_data_23_V_read");
    sc_trace(mVcdFile, data_stream_V_data_24_V_dout, "(port)data_stream_V_data_24_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_24_V_empty_n, "(port)data_stream_V_data_24_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_24_V_read, "(port)data_stream_V_data_24_V_read");
    sc_trace(mVcdFile, data_stream_V_data_25_V_dout, "(port)data_stream_V_data_25_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_25_V_empty_n, "(port)data_stream_V_data_25_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_25_V_read, "(port)data_stream_V_data_25_V_read");
    sc_trace(mVcdFile, data_stream_V_data_26_V_dout, "(port)data_stream_V_data_26_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_26_V_empty_n, "(port)data_stream_V_data_26_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_26_V_read, "(port)data_stream_V_data_26_V_read");
    sc_trace(mVcdFile, data_stream_V_data_27_V_dout, "(port)data_stream_V_data_27_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_27_V_empty_n, "(port)data_stream_V_data_27_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_27_V_read, "(port)data_stream_V_data_27_V_read");
    sc_trace(mVcdFile, data_stream_V_data_28_V_dout, "(port)data_stream_V_data_28_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_28_V_empty_n, "(port)data_stream_V_data_28_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_28_V_read, "(port)data_stream_V_data_28_V_read");
    sc_trace(mVcdFile, data_stream_V_data_29_V_dout, "(port)data_stream_V_data_29_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_29_V_empty_n, "(port)data_stream_V_data_29_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_29_V_read, "(port)data_stream_V_data_29_V_read");
    sc_trace(mVcdFile, data_stream_V_data_30_V_dout, "(port)data_stream_V_data_30_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_30_V_empty_n, "(port)data_stream_V_data_30_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_30_V_read, "(port)data_stream_V_data_30_V_read");
    sc_trace(mVcdFile, data_stream_V_data_31_V_dout, "(port)data_stream_V_data_31_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_31_V_empty_n, "(port)data_stream_V_data_31_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_31_V_read, "(port)data_stream_V_data_31_V_read");
    sc_trace(mVcdFile, res_stream_V_data_0_V_din, "(port)res_stream_V_data_0_V_din");
    sc_trace(mVcdFile, res_stream_V_data_0_V_full_n, "(port)res_stream_V_data_0_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_0_V_write, "(port)res_stream_V_data_0_V_write");
    sc_trace(mVcdFile, res_stream_V_data_1_V_din, "(port)res_stream_V_data_1_V_din");
    sc_trace(mVcdFile, res_stream_V_data_1_V_full_n, "(port)res_stream_V_data_1_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_1_V_write, "(port)res_stream_V_data_1_V_write");
    sc_trace(mVcdFile, res_stream_V_data_2_V_din, "(port)res_stream_V_data_2_V_din");
    sc_trace(mVcdFile, res_stream_V_data_2_V_full_n, "(port)res_stream_V_data_2_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_2_V_write, "(port)res_stream_V_data_2_V_write");
    sc_trace(mVcdFile, res_stream_V_data_3_V_din, "(port)res_stream_V_data_3_V_din");
    sc_trace(mVcdFile, res_stream_V_data_3_V_full_n, "(port)res_stream_V_data_3_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_3_V_write, "(port)res_stream_V_data_3_V_write");
    sc_trace(mVcdFile, res_stream_V_data_4_V_din, "(port)res_stream_V_data_4_V_din");
    sc_trace(mVcdFile, res_stream_V_data_4_V_full_n, "(port)res_stream_V_data_4_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_4_V_write, "(port)res_stream_V_data_4_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, data_stream_V_data_0_V_blk_n, "data_stream_V_data_0_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_1_V_blk_n, "data_stream_V_data_1_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_2_V_blk_n, "data_stream_V_data_2_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_3_V_blk_n, "data_stream_V_data_3_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_4_V_blk_n, "data_stream_V_data_4_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_5_V_blk_n, "data_stream_V_data_5_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_6_V_blk_n, "data_stream_V_data_6_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_7_V_blk_n, "data_stream_V_data_7_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_8_V_blk_n, "data_stream_V_data_8_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_9_V_blk_n, "data_stream_V_data_9_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_10_V_blk_n, "data_stream_V_data_10_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_11_V_blk_n, "data_stream_V_data_11_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_12_V_blk_n, "data_stream_V_data_12_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_13_V_blk_n, "data_stream_V_data_13_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_14_V_blk_n, "data_stream_V_data_14_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_15_V_blk_n, "data_stream_V_data_15_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_16_V_blk_n, "data_stream_V_data_16_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_17_V_blk_n, "data_stream_V_data_17_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_18_V_blk_n, "data_stream_V_data_18_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_19_V_blk_n, "data_stream_V_data_19_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_20_V_blk_n, "data_stream_V_data_20_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_21_V_blk_n, "data_stream_V_data_21_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_22_V_blk_n, "data_stream_V_data_22_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_23_V_blk_n, "data_stream_V_data_23_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_24_V_blk_n, "data_stream_V_data_24_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_25_V_blk_n, "data_stream_V_data_25_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_26_V_blk_n, "data_stream_V_data_26_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_27_V_blk_n, "data_stream_V_data_27_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_28_V_blk_n, "data_stream_V_data_28_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_29_V_blk_n, "data_stream_V_data_29_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_30_V_blk_n, "data_stream_V_data_30_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_31_V_blk_n, "data_stream_V_data_31_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_0_V_blk_n, "res_stream_V_data_0_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, res_stream_V_data_1_V_blk_n, "res_stream_V_data_1_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_2_V_blk_n, "res_stream_V_data_2_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_3_V_blk_n, "res_stream_V_data_3_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_4_V_blk_n, "res_stream_V_data_4_V_blk_n");
    sc_trace(mVcdFile, data_0_V_reg_811, "data_0_V_reg_811");
    sc_trace(mVcdFile, io_acc_block_signal_op5, "io_acc_block_signal_op5");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, data_1_V_reg_816, "data_1_V_reg_816");
    sc_trace(mVcdFile, data_2_V_reg_821, "data_2_V_reg_821");
    sc_trace(mVcdFile, data_3_V_reg_826, "data_3_V_reg_826");
    sc_trace(mVcdFile, data_4_V_reg_831, "data_4_V_reg_831");
    sc_trace(mVcdFile, data_5_V_reg_836, "data_5_V_reg_836");
    sc_trace(mVcdFile, data_6_V_reg_841, "data_6_V_reg_841");
    sc_trace(mVcdFile, data_7_V_reg_846, "data_7_V_reg_846");
    sc_trace(mVcdFile, data_8_V_reg_851, "data_8_V_reg_851");
    sc_trace(mVcdFile, data_9_V_reg_856, "data_9_V_reg_856");
    sc_trace(mVcdFile, data_10_V_reg_861, "data_10_V_reg_861");
    sc_trace(mVcdFile, data_11_V_reg_866, "data_11_V_reg_866");
    sc_trace(mVcdFile, data_12_V_reg_871, "data_12_V_reg_871");
    sc_trace(mVcdFile, data_13_V_reg_876, "data_13_V_reg_876");
    sc_trace(mVcdFile, data_14_V_reg_881, "data_14_V_reg_881");
    sc_trace(mVcdFile, data_15_V_reg_886, "data_15_V_reg_886");
    sc_trace(mVcdFile, data_16_V_reg_891, "data_16_V_reg_891");
    sc_trace(mVcdFile, data_17_V_reg_896, "data_17_V_reg_896");
    sc_trace(mVcdFile, data_18_V_reg_901, "data_18_V_reg_901");
    sc_trace(mVcdFile, data_19_V_reg_906, "data_19_V_reg_906");
    sc_trace(mVcdFile, data_20_V_reg_911, "data_20_V_reg_911");
    sc_trace(mVcdFile, data_21_V_reg_916, "data_21_V_reg_916");
    sc_trace(mVcdFile, data_22_V_reg_921, "data_22_V_reg_921");
    sc_trace(mVcdFile, data_23_V_reg_926, "data_23_V_reg_926");
    sc_trace(mVcdFile, data_24_V_reg_931, "data_24_V_reg_931");
    sc_trace(mVcdFile, data_25_V_reg_936, "data_25_V_reg_936");
    sc_trace(mVcdFile, data_26_V_reg_941, "data_26_V_reg_941");
    sc_trace(mVcdFile, data_27_V_reg_946, "data_27_V_reg_946");
    sc_trace(mVcdFile, data_28_V_reg_951, "data_28_V_reg_951");
    sc_trace(mVcdFile, data_29_V_reg_956, "data_29_V_reg_956");
    sc_trace(mVcdFile, data_30_V_reg_961, "data_30_V_reg_961");
    sc_trace(mVcdFile, data_31_V_reg_966, "data_31_V_reg_966");
    sc_trace(mVcdFile, tmp_data_0_V_reg_971, "tmp_data_0_V_reg_971");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_data_1_V_reg_976, "tmp_data_1_V_reg_976");
    sc_trace(mVcdFile, tmp_data_2_V_reg_981, "tmp_data_2_V_reg_981");
    sc_trace(mVcdFile, tmp_data_3_V_reg_986, "tmp_data_3_V_reg_986");
    sc_trace(mVcdFile, tmp_data_4_V_reg_991, "tmp_data_4_V_reg_991");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_0, "grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_0");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_1, "grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_1");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_2, "grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_2");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_3, "grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_3");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_4, "grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_4");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, io_acc_block_signal_op84, "io_acc_block_signal_op84");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::~dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627;
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(io_acc_block_signal_op84.read(), ap_const_logic_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_0_V_reg_811 = data_stream_V_data_0_V_dout.read();
        data_10_V_reg_861 = data_stream_V_data_10_V_dout.read();
        data_11_V_reg_866 = data_stream_V_data_11_V_dout.read();
        data_12_V_reg_871 = data_stream_V_data_12_V_dout.read();
        data_13_V_reg_876 = data_stream_V_data_13_V_dout.read();
        data_14_V_reg_881 = data_stream_V_data_14_V_dout.read();
        data_15_V_reg_886 = data_stream_V_data_15_V_dout.read();
        data_16_V_reg_891 = data_stream_V_data_16_V_dout.read();
        data_17_V_reg_896 = data_stream_V_data_17_V_dout.read();
        data_18_V_reg_901 = data_stream_V_data_18_V_dout.read();
        data_19_V_reg_906 = data_stream_V_data_19_V_dout.read();
        data_1_V_reg_816 = data_stream_V_data_1_V_dout.read();
        data_20_V_reg_911 = data_stream_V_data_20_V_dout.read();
        data_21_V_reg_916 = data_stream_V_data_21_V_dout.read();
        data_22_V_reg_921 = data_stream_V_data_22_V_dout.read();
        data_23_V_reg_926 = data_stream_V_data_23_V_dout.read();
        data_24_V_reg_931 = data_stream_V_data_24_V_dout.read();
        data_25_V_reg_936 = data_stream_V_data_25_V_dout.read();
        data_26_V_reg_941 = data_stream_V_data_26_V_dout.read();
        data_27_V_reg_946 = data_stream_V_data_27_V_dout.read();
        data_28_V_reg_951 = data_stream_V_data_28_V_dout.read();
        data_29_V_reg_956 = data_stream_V_data_29_V_dout.read();
        data_2_V_reg_821 = data_stream_V_data_2_V_dout.read();
        data_30_V_reg_961 = data_stream_V_data_30_V_dout.read();
        data_31_V_reg_966 = data_stream_V_data_31_V_dout.read();
        data_3_V_reg_826 = data_stream_V_data_3_V_dout.read();
        data_4_V_reg_831 = data_stream_V_data_4_V_dout.read();
        data_5_V_reg_836 = data_stream_V_data_5_V_dout.read();
        data_6_V_reg_841 = data_stream_V_data_6_V_dout.read();
        data_7_V_reg_846 = data_stream_V_data_7_V_dout.read();
        data_8_V_reg_851 = data_stream_V_data_8_V_dout.read();
        data_9_V_reg_856 = data_stream_V_data_9_V_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_data_0_V_reg_971 = grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_0.read();
        tmp_data_1_V_reg_976 = grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_1.read();
        tmp_data_2_V_reg_981 = grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_2.read();
        tmp_data_3_V_reg_986 = grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_3.read();
        tmp_data_4_V_reg_991 = grp_dense_wrapper_ap_ufixed_8_0_4_0_0_ap_fixed_22_7_5_3_0_config16_s_fu_627_ap_return_4.read();
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read()));
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op84.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_0_V_blk_n = data_stream_V_data_0_V_empty_n.read();
    } else {
        data_stream_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_0_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_0_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_10_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_10_V_blk_n = data_stream_V_data_10_V_empty_n.read();
    } else {
        data_stream_V_data_10_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_10_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_10_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_10_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_11_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_11_V_blk_n = data_stream_V_data_11_V_empty_n.read();
    } else {
        data_stream_V_data_11_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_11_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_11_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_11_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_12_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_12_V_blk_n = data_stream_V_data_12_V_empty_n.read();
    } else {
        data_stream_V_data_12_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_12_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_12_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_12_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_13_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_13_V_blk_n = data_stream_V_data_13_V_empty_n.read();
    } else {
        data_stream_V_data_13_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_13_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_13_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_13_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_14_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_14_V_blk_n = data_stream_V_data_14_V_empty_n.read();
    } else {
        data_stream_V_data_14_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_14_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_14_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_14_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_15_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_15_V_blk_n = data_stream_V_data_15_V_empty_n.read();
    } else {
        data_stream_V_data_15_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_15_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_15_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_15_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_16_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_16_V_blk_n = data_stream_V_data_16_V_empty_n.read();
    } else {
        data_stream_V_data_16_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_16_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_16_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_16_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_17_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_17_V_blk_n = data_stream_V_data_17_V_empty_n.read();
    } else {
        data_stream_V_data_17_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_17_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_17_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_17_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_18_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_18_V_blk_n = data_stream_V_data_18_V_empty_n.read();
    } else {
        data_stream_V_data_18_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_18_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_18_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_18_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_19_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_19_V_blk_n = data_stream_V_data_19_V_empty_n.read();
    } else {
        data_stream_V_data_19_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_19_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_19_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_19_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_1_V_blk_n = data_stream_V_data_1_V_empty_n.read();
    } else {
        data_stream_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_1_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_1_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_20_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_20_V_blk_n = data_stream_V_data_20_V_empty_n.read();
    } else {
        data_stream_V_data_20_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_20_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_20_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_20_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_21_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_21_V_blk_n = data_stream_V_data_21_V_empty_n.read();
    } else {
        data_stream_V_data_21_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_21_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_21_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_21_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_22_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_22_V_blk_n = data_stream_V_data_22_V_empty_n.read();
    } else {
        data_stream_V_data_22_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_22_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_22_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_22_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_23_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_23_V_blk_n = data_stream_V_data_23_V_empty_n.read();
    } else {
        data_stream_V_data_23_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_23_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_23_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_23_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_24_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_24_V_blk_n = data_stream_V_data_24_V_empty_n.read();
    } else {
        data_stream_V_data_24_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_24_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_24_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_24_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_25_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_25_V_blk_n = data_stream_V_data_25_V_empty_n.read();
    } else {
        data_stream_V_data_25_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_25_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_25_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_25_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_26_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_26_V_blk_n = data_stream_V_data_26_V_empty_n.read();
    } else {
        data_stream_V_data_26_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_26_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_26_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_26_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_27_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_27_V_blk_n = data_stream_V_data_27_V_empty_n.read();
    } else {
        data_stream_V_data_27_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_27_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_27_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_27_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_28_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_28_V_blk_n = data_stream_V_data_28_V_empty_n.read();
    } else {
        data_stream_V_data_28_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_28_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_28_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_28_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_29_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_29_V_blk_n = data_stream_V_data_29_V_empty_n.read();
    } else {
        data_stream_V_data_29_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_29_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_29_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_29_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_2_V_blk_n = data_stream_V_data_2_V_empty_n.read();
    } else {
        data_stream_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_2_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_2_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_30_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_30_V_blk_n = data_stream_V_data_30_V_empty_n.read();
    } else {
        data_stream_V_data_30_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_30_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_30_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_30_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_31_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_31_V_blk_n = data_stream_V_data_31_V_empty_n.read();
    } else {
        data_stream_V_data_31_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_31_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_31_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_31_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_3_V_blk_n = data_stream_V_data_3_V_empty_n.read();
    } else {
        data_stream_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_3_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_3_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_3_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_4_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_4_V_blk_n = data_stream_V_data_4_V_empty_n.read();
    } else {
        data_stream_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_4_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_4_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_4_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_5_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_5_V_blk_n = data_stream_V_data_5_V_empty_n.read();
    } else {
        data_stream_V_data_5_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_5_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_5_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_5_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_6_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_6_V_blk_n = data_stream_V_data_6_V_empty_n.read();
    } else {
        data_stream_V_data_6_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_6_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_6_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_6_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_7_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_7_V_blk_n = data_stream_V_data_7_V_empty_n.read();
    } else {
        data_stream_V_data_7_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_7_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_7_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_7_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_8_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_8_V_blk_n = data_stream_V_data_8_V_empty_n.read();
    } else {
        data_stream_V_data_8_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_8_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_8_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_8_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_9_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_stream_V_data_9_V_blk_n = data_stream_V_data_9_V_empty_n.read();
    } else {
        data_stream_V_data_9_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_data_stream_V_data_9_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
        data_stream_V_data_9_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_9_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op84.read(), ap_const_logic_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_io_acc_block_signal_op5() {
    io_acc_block_signal_op5 = (data_stream_V_data_0_V_empty_n.read() & data_stream_V_data_1_V_empty_n.read() & data_stream_V_data_2_V_empty_n.read() & data_stream_V_data_3_V_empty_n.read() & data_stream_V_data_4_V_empty_n.read() & data_stream_V_data_5_V_empty_n.read() & data_stream_V_data_6_V_empty_n.read() & data_stream_V_data_7_V_empty_n.read() & data_stream_V_data_8_V_empty_n.read() & data_stream_V_data_9_V_empty_n.read() & data_stream_V_data_10_V_empty_n.read() & data_stream_V_data_11_V_empty_n.read() & data_stream_V_data_12_V_empty_n.read() & data_stream_V_data_13_V_empty_n.read() & data_stream_V_data_14_V_empty_n.read() & data_stream_V_data_15_V_empty_n.read() & data_stream_V_data_16_V_empty_n.read() & data_stream_V_data_17_V_empty_n.read() & data_stream_V_data_18_V_empty_n.read() & data_stream_V_data_19_V_empty_n.read() & data_stream_V_data_20_V_empty_n.read() & data_stream_V_data_21_V_empty_n.read() & data_stream_V_data_22_V_empty_n.read() & data_stream_V_data_23_V_empty_n.read() & data_stream_V_data_24_V_empty_n.read() & data_stream_V_data_25_V_empty_n.read() & data_stream_V_data_26_V_empty_n.read() & data_stream_V_data_27_V_empty_n.read() & data_stream_V_data_28_V_empty_n.read() & data_stream_V_data_29_V_empty_n.read() & data_stream_V_data_30_V_empty_n.read() & data_stream_V_data_31_V_empty_n.read());
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_io_acc_block_signal_op84() {
    io_acc_block_signal_op84 = (res_stream_V_data_0_V_full_n.read() & res_stream_V_data_1_V_full_n.read() & res_stream_V_data_2_V_full_n.read() & res_stream_V_data_3_V_full_n.read() & res_stream_V_data_4_V_full_n.read());
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_0_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        res_stream_V_data_0_V_blk_n = res_stream_V_data_0_V_full_n.read();
    } else {
        res_stream_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_0_V_din() {
    res_stream_V_data_0_V_din = tmp_data_0_V_reg_971.read();
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op84.read(), ap_const_logic_1))) {
        res_stream_V_data_0_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_0_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_1_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        res_stream_V_data_1_V_blk_n = res_stream_V_data_1_V_full_n.read();
    } else {
        res_stream_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_1_V_din() {
    res_stream_V_data_1_V_din = tmp_data_1_V_reg_976.read();
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op84.read(), ap_const_logic_1))) {
        res_stream_V_data_1_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_1_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_2_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        res_stream_V_data_2_V_blk_n = res_stream_V_data_2_V_full_n.read();
    } else {
        res_stream_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_2_V_din() {
    res_stream_V_data_2_V_din = tmp_data_2_V_reg_981.read();
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op84.read(), ap_const_logic_1))) {
        res_stream_V_data_2_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_2_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_3_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        res_stream_V_data_3_V_blk_n = res_stream_V_data_3_V_full_n.read();
    } else {
        res_stream_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_3_V_din() {
    res_stream_V_data_3_V_din = tmp_data_3_V_reg_986.read();
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_3_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op84.read(), ap_const_logic_1))) {
        res_stream_V_data_3_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_3_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_4_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        res_stream_V_data_4_V_blk_n = res_stream_V_data_4_V_full_n.read();
    } else {
        res_stream_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_4_V_din() {
    res_stream_V_data_4_V_din = tmp_data_4_V_reg_991.read();
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_res_stream_V_data_4_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op84.read(), ap_const_logic_1))) {
        res_stream_V_data_4_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_4_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_start_out() {
    start_out = real_start.read();
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void dense_array_ap_ufixed_32u_array_ap_fixed_22_7_5_3_0_5u_config16_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op5.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(io_acc_block_signal_op84.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

