

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparse_input_U0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mul_12s_8ns_19_1_1_U2"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mul_12s_7ns_18_1_1_U3"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mul_12s_7ns_18_1_1_U4"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mul_12s_7ns_18_1_1_U5"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mul_12s_7ns_18_1_1_U6"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mul_12s_7ns_18_1_1_U7"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mul_12s_6ns_17_1_1_U8"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mul_12s_5s_17_1_1_U9"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mac_muladd_12s_6ns_19s_20_1_1_U10"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mac_muladd_12s_6ns_20s_20_1_1_U11"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mac_muladd_12s_6ns_20s_20_1_1_U12"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sparse_compute_U0.mac_muladd_12s_6ns_20s_20_1_1_U13"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry16_proc_U0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry17_proc_U0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_U"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_1_U"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_2_U"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_3_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_4_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_5_U"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_6_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_7_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_8_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_9_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hash_arr_10_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.newret21_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_arr_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_arr_1_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_arr_2_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_arr_3_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_arr_4_U"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_arr_5_U"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_arr_6_U"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_arr_7_U"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_arr_8_U"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_out_channel_U"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat_out_load_loc_channel_U"}]}
set DependenceCheckSize 0
