// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module model_test_conv_2d_cl_ap_fixed_12_4_0_0_0_ap_fixed_25_10_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        x_in,
        x_in_ap_vld,
        layer2_out_0,
        layer2_out_0_ap_vld,
        layer2_out_1,
        layer2_out_1_ap_vld,
        layer2_out_2,
        layer2_out_2_ap_vld,
        layer2_out_3,
        layer2_out_3_ap_vld,
        layer2_out_4,
        layer2_out_4_ap_vld,
        layer2_out_5,
        layer2_out_5_ap_vld,
        layer2_out_6,
        layer2_out_6_ap_vld,
        layer2_out_7,
        layer2_out_7_ap_vld,
        layer2_out_8,
        layer2_out_8_ap_vld,
        layer2_out_9,
        layer2_out_9_ap_vld,
        layer2_out_10,
        layer2_out_10_ap_vld,
        layer2_out_11,
        layer2_out_11_ap_vld,
        layer2_out_12,
        layer2_out_12_ap_vld,
        layer2_out_13,
        layer2_out_13_ap_vld,
        layer2_out_14,
        layer2_out_14_ap_vld,
        layer2_out_15,
        layer2_out_15_ap_vld,
        layer2_out_16,
        layer2_out_16_ap_vld,
        layer2_out_17,
        layer2_out_17_ap_vld,
        layer2_out_18,
        layer2_out_18_ap_vld,
        layer2_out_19,
        layer2_out_19_ap_vld,
        layer2_out_20,
        layer2_out_20_ap_vld,
        layer2_out_21,
        layer2_out_21_ap_vld,
        layer2_out_22,
        layer2_out_22_ap_vld,
        layer2_out_23,
        layer2_out_23_ap_vld,
        layer2_out_24,
        layer2_out_24_ap_vld,
        layer2_out_25,
        layer2_out_25_ap_vld,
        layer2_out_26,
        layer2_out_26_ap_vld,
        layer2_out_27,
        layer2_out_27_ap_vld,
        layer2_out_28,
        layer2_out_28_ap_vld,
        layer2_out_29,
        layer2_out_29_ap_vld,
        layer2_out_30,
        layer2_out_30_ap_vld,
        layer2_out_31,
        layer2_out_31_ap_vld,
        layer2_out_32,
        layer2_out_32_ap_vld,
        layer2_out_33,
        layer2_out_33_ap_vld,
        layer2_out_34,
        layer2_out_34_ap_vld,
        layer2_out_35,
        layer2_out_35_ap_vld,
        layer2_out_36,
        layer2_out_36_ap_vld,
        layer2_out_37,
        layer2_out_37_ap_vld,
        layer2_out_38,
        layer2_out_38_ap_vld,
        layer2_out_39,
        layer2_out_39_ap_vld,
        layer2_out_40,
        layer2_out_40_ap_vld,
        layer2_out_41,
        layer2_out_41_ap_vld,
        layer2_out_42,
        layer2_out_42_ap_vld,
        layer2_out_43,
        layer2_out_43_ap_vld,
        layer2_out_44,
        layer2_out_44_ap_vld,
        layer2_out_45,
        layer2_out_45_ap_vld,
        layer2_out_46,
        layer2_out_46_ap_vld,
        layer2_out_47,
        layer2_out_47_ap_vld,
        layer2_out_48,
        layer2_out_48_ap_vld,
        layer2_out_49,
        layer2_out_49_ap_vld,
        layer2_out_50,
        layer2_out_50_ap_vld,
        layer2_out_51,
        layer2_out_51_ap_vld,
        layer2_out_52,
        layer2_out_52_ap_vld,
        layer2_out_53,
        layer2_out_53_ap_vld,
        layer2_out_54,
        layer2_out_54_ap_vld,
        layer2_out_55,
        layer2_out_55_ap_vld,
        layer2_out_56,
        layer2_out_56_ap_vld,
        layer2_out_57,
        layer2_out_57_ap_vld,
        layer2_out_58,
        layer2_out_58_ap_vld,
        layer2_out_59,
        layer2_out_59_ap_vld,
        layer2_out_60,
        layer2_out_60_ap_vld,
        layer2_out_61,
        layer2_out_61_ap_vld,
        layer2_out_62,
        layer2_out_62_ap_vld,
        layer2_out_63,
        layer2_out_63_ap_vld,
        layer2_out_64,
        layer2_out_64_ap_vld,
        layer2_out_65,
        layer2_out_65_ap_vld,
        layer2_out_66,
        layer2_out_66_ap_vld,
        layer2_out_67,
        layer2_out_67_ap_vld,
        layer2_out_68,
        layer2_out_68_ap_vld,
        layer2_out_69,
        layer2_out_69_ap_vld,
        layer2_out_70,
        layer2_out_70_ap_vld,
        layer2_out_71,
        layer2_out_71_ap_vld,
        layer2_out_72,
        layer2_out_72_ap_vld,
        layer2_out_73,
        layer2_out_73_ap_vld,
        layer2_out_74,
        layer2_out_74_ap_vld,
        layer2_out_75,
        layer2_out_75_ap_vld,
        layer2_out_76,
        layer2_out_76_ap_vld,
        layer2_out_77,
        layer2_out_77_ap_vld,
        layer2_out_78,
        layer2_out_78_ap_vld,
        layer2_out_79,
        layer2_out_79_ap_vld,
        layer2_out_80,
        layer2_out_80_ap_vld,
        layer2_out_81,
        layer2_out_81_ap_vld,
        layer2_out_82,
        layer2_out_82_ap_vld,
        layer2_out_83,
        layer2_out_83_ap_vld,
        layer2_out_84,
        layer2_out_84_ap_vld,
        layer2_out_85,
        layer2_out_85_ap_vld,
        layer2_out_86,
        layer2_out_86_ap_vld,
        layer2_out_87,
        layer2_out_87_ap_vld,
        layer2_out_88,
        layer2_out_88_ap_vld,
        layer2_out_89,
        layer2_out_89_ap_vld,
        layer2_out_90,
        layer2_out_90_ap_vld,
        layer2_out_91,
        layer2_out_91_ap_vld,
        layer2_out_92,
        layer2_out_92_ap_vld,
        layer2_out_93,
        layer2_out_93_ap_vld,
        layer2_out_94,
        layer2_out_94_ap_vld,
        layer2_out_95,
        layer2_out_95_ap_vld,
        layer2_out_96,
        layer2_out_96_ap_vld,
        layer2_out_97,
        layer2_out_97_ap_vld,
        layer2_out_98,
        layer2_out_98_ap_vld,
        layer2_out_99,
        layer2_out_99_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1199:0] x_in;
input   x_in_ap_vld;
output  [24:0] layer2_out_0;
output   layer2_out_0_ap_vld;
output  [24:0] layer2_out_1;
output   layer2_out_1_ap_vld;
output  [24:0] layer2_out_2;
output   layer2_out_2_ap_vld;
output  [24:0] layer2_out_3;
output   layer2_out_3_ap_vld;
output  [24:0] layer2_out_4;
output   layer2_out_4_ap_vld;
output  [24:0] layer2_out_5;
output   layer2_out_5_ap_vld;
output  [24:0] layer2_out_6;
output   layer2_out_6_ap_vld;
output  [24:0] layer2_out_7;
output   layer2_out_7_ap_vld;
output  [24:0] layer2_out_8;
output   layer2_out_8_ap_vld;
output  [24:0] layer2_out_9;
output   layer2_out_9_ap_vld;
output  [24:0] layer2_out_10;
output   layer2_out_10_ap_vld;
output  [24:0] layer2_out_11;
output   layer2_out_11_ap_vld;
output  [24:0] layer2_out_12;
output   layer2_out_12_ap_vld;
output  [24:0] layer2_out_13;
output   layer2_out_13_ap_vld;
output  [24:0] layer2_out_14;
output   layer2_out_14_ap_vld;
output  [24:0] layer2_out_15;
output   layer2_out_15_ap_vld;
output  [24:0] layer2_out_16;
output   layer2_out_16_ap_vld;
output  [24:0] layer2_out_17;
output   layer2_out_17_ap_vld;
output  [24:0] layer2_out_18;
output   layer2_out_18_ap_vld;
output  [24:0] layer2_out_19;
output   layer2_out_19_ap_vld;
output  [24:0] layer2_out_20;
output   layer2_out_20_ap_vld;
output  [24:0] layer2_out_21;
output   layer2_out_21_ap_vld;
output  [24:0] layer2_out_22;
output   layer2_out_22_ap_vld;
output  [24:0] layer2_out_23;
output   layer2_out_23_ap_vld;
output  [24:0] layer2_out_24;
output   layer2_out_24_ap_vld;
output  [24:0] layer2_out_25;
output   layer2_out_25_ap_vld;
output  [24:0] layer2_out_26;
output   layer2_out_26_ap_vld;
output  [24:0] layer2_out_27;
output   layer2_out_27_ap_vld;
output  [24:0] layer2_out_28;
output   layer2_out_28_ap_vld;
output  [24:0] layer2_out_29;
output   layer2_out_29_ap_vld;
output  [24:0] layer2_out_30;
output   layer2_out_30_ap_vld;
output  [24:0] layer2_out_31;
output   layer2_out_31_ap_vld;
output  [24:0] layer2_out_32;
output   layer2_out_32_ap_vld;
output  [24:0] layer2_out_33;
output   layer2_out_33_ap_vld;
output  [24:0] layer2_out_34;
output   layer2_out_34_ap_vld;
output  [24:0] layer2_out_35;
output   layer2_out_35_ap_vld;
output  [24:0] layer2_out_36;
output   layer2_out_36_ap_vld;
output  [24:0] layer2_out_37;
output   layer2_out_37_ap_vld;
output  [24:0] layer2_out_38;
output   layer2_out_38_ap_vld;
output  [24:0] layer2_out_39;
output   layer2_out_39_ap_vld;
output  [24:0] layer2_out_40;
output   layer2_out_40_ap_vld;
output  [24:0] layer2_out_41;
output   layer2_out_41_ap_vld;
output  [24:0] layer2_out_42;
output   layer2_out_42_ap_vld;
output  [24:0] layer2_out_43;
output   layer2_out_43_ap_vld;
output  [24:0] layer2_out_44;
output   layer2_out_44_ap_vld;
output  [24:0] layer2_out_45;
output   layer2_out_45_ap_vld;
output  [24:0] layer2_out_46;
output   layer2_out_46_ap_vld;
output  [24:0] layer2_out_47;
output   layer2_out_47_ap_vld;
output  [24:0] layer2_out_48;
output   layer2_out_48_ap_vld;
output  [24:0] layer2_out_49;
output   layer2_out_49_ap_vld;
output  [24:0] layer2_out_50;
output   layer2_out_50_ap_vld;
output  [24:0] layer2_out_51;
output   layer2_out_51_ap_vld;
output  [24:0] layer2_out_52;
output   layer2_out_52_ap_vld;
output  [24:0] layer2_out_53;
output   layer2_out_53_ap_vld;
output  [24:0] layer2_out_54;
output   layer2_out_54_ap_vld;
output  [24:0] layer2_out_55;
output   layer2_out_55_ap_vld;
output  [24:0] layer2_out_56;
output   layer2_out_56_ap_vld;
output  [24:0] layer2_out_57;
output   layer2_out_57_ap_vld;
output  [24:0] layer2_out_58;
output   layer2_out_58_ap_vld;
output  [24:0] layer2_out_59;
output   layer2_out_59_ap_vld;
output  [24:0] layer2_out_60;
output   layer2_out_60_ap_vld;
output  [24:0] layer2_out_61;
output   layer2_out_61_ap_vld;
output  [24:0] layer2_out_62;
output   layer2_out_62_ap_vld;
output  [24:0] layer2_out_63;
output   layer2_out_63_ap_vld;
output  [24:0] layer2_out_64;
output   layer2_out_64_ap_vld;
output  [24:0] layer2_out_65;
output   layer2_out_65_ap_vld;
output  [24:0] layer2_out_66;
output   layer2_out_66_ap_vld;
output  [24:0] layer2_out_67;
output   layer2_out_67_ap_vld;
output  [24:0] layer2_out_68;
output   layer2_out_68_ap_vld;
output  [24:0] layer2_out_69;
output   layer2_out_69_ap_vld;
output  [24:0] layer2_out_70;
output   layer2_out_70_ap_vld;
output  [24:0] layer2_out_71;
output   layer2_out_71_ap_vld;
output  [24:0] layer2_out_72;
output   layer2_out_72_ap_vld;
output  [24:0] layer2_out_73;
output   layer2_out_73_ap_vld;
output  [24:0] layer2_out_74;
output   layer2_out_74_ap_vld;
output  [24:0] layer2_out_75;
output   layer2_out_75_ap_vld;
output  [24:0] layer2_out_76;
output   layer2_out_76_ap_vld;
output  [24:0] layer2_out_77;
output   layer2_out_77_ap_vld;
output  [24:0] layer2_out_78;
output   layer2_out_78_ap_vld;
output  [24:0] layer2_out_79;
output   layer2_out_79_ap_vld;
output  [24:0] layer2_out_80;
output   layer2_out_80_ap_vld;
output  [24:0] layer2_out_81;
output   layer2_out_81_ap_vld;
output  [24:0] layer2_out_82;
output   layer2_out_82_ap_vld;
output  [24:0] layer2_out_83;
output   layer2_out_83_ap_vld;
output  [24:0] layer2_out_84;
output   layer2_out_84_ap_vld;
output  [24:0] layer2_out_85;
output   layer2_out_85_ap_vld;
output  [24:0] layer2_out_86;
output   layer2_out_86_ap_vld;
output  [24:0] layer2_out_87;
output   layer2_out_87_ap_vld;
output  [24:0] layer2_out_88;
output   layer2_out_88_ap_vld;
output  [24:0] layer2_out_89;
output   layer2_out_89_ap_vld;
output  [24:0] layer2_out_90;
output   layer2_out_90_ap_vld;
output  [24:0] layer2_out_91;
output   layer2_out_91_ap_vld;
output  [24:0] layer2_out_92;
output   layer2_out_92_ap_vld;
output  [24:0] layer2_out_93;
output   layer2_out_93_ap_vld;
output  [24:0] layer2_out_94;
output   layer2_out_94_ap_vld;
output  [24:0] layer2_out_95;
output   layer2_out_95_ap_vld;
output  [24:0] layer2_out_96;
output   layer2_out_96_ap_vld;
output  [24:0] layer2_out_97;
output   layer2_out_97_ap_vld;
output  [24:0] layer2_out_98;
output   layer2_out_98_ap_vld;
output  [24:0] layer2_out_99;
output   layer2_out_99_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[24:0] layer2_out_0;
reg layer2_out_0_ap_vld;
reg layer2_out_1_ap_vld;
reg layer2_out_2_ap_vld;
reg layer2_out_3_ap_vld;
reg layer2_out_4_ap_vld;
reg layer2_out_5_ap_vld;
reg layer2_out_6_ap_vld;
reg layer2_out_7_ap_vld;
reg layer2_out_8_ap_vld;
reg layer2_out_9_ap_vld;
reg layer2_out_10_ap_vld;
reg layer2_out_11_ap_vld;
reg layer2_out_12_ap_vld;
reg layer2_out_13_ap_vld;
reg layer2_out_14_ap_vld;
reg layer2_out_15_ap_vld;
reg layer2_out_16_ap_vld;
reg layer2_out_17_ap_vld;
reg layer2_out_18_ap_vld;
reg layer2_out_19_ap_vld;
reg layer2_out_20_ap_vld;
reg layer2_out_21_ap_vld;
reg layer2_out_22_ap_vld;
reg layer2_out_23_ap_vld;
reg layer2_out_24_ap_vld;
reg layer2_out_25_ap_vld;
reg layer2_out_26_ap_vld;
reg layer2_out_27_ap_vld;
reg layer2_out_28_ap_vld;
reg layer2_out_29_ap_vld;
reg layer2_out_30_ap_vld;
reg layer2_out_31_ap_vld;
reg layer2_out_32_ap_vld;
reg layer2_out_33_ap_vld;
reg layer2_out_34_ap_vld;
reg layer2_out_35_ap_vld;
reg layer2_out_36_ap_vld;
reg layer2_out_37_ap_vld;
reg layer2_out_38_ap_vld;
reg layer2_out_39_ap_vld;
reg layer2_out_40_ap_vld;
reg layer2_out_41_ap_vld;
reg layer2_out_42_ap_vld;
reg layer2_out_43_ap_vld;
reg layer2_out_44_ap_vld;
reg layer2_out_45_ap_vld;
reg layer2_out_46_ap_vld;
reg layer2_out_47_ap_vld;
reg layer2_out_48_ap_vld;
reg layer2_out_49_ap_vld;
reg layer2_out_50_ap_vld;
reg layer2_out_51_ap_vld;
reg layer2_out_52_ap_vld;
reg layer2_out_53_ap_vld;
reg layer2_out_54_ap_vld;
reg layer2_out_55_ap_vld;
reg layer2_out_56_ap_vld;
reg layer2_out_57_ap_vld;
reg layer2_out_58_ap_vld;
reg layer2_out_59_ap_vld;
reg layer2_out_60_ap_vld;
reg layer2_out_61_ap_vld;
reg layer2_out_62_ap_vld;
reg layer2_out_63_ap_vld;
reg layer2_out_64_ap_vld;
reg layer2_out_65_ap_vld;
reg layer2_out_66_ap_vld;
reg layer2_out_67_ap_vld;
reg layer2_out_68_ap_vld;
reg layer2_out_69_ap_vld;
reg layer2_out_70_ap_vld;
reg layer2_out_71_ap_vld;
reg layer2_out_72_ap_vld;
reg layer2_out_73_ap_vld;
reg layer2_out_74_ap_vld;
reg layer2_out_75_ap_vld;
reg layer2_out_76_ap_vld;
reg layer2_out_77_ap_vld;
reg layer2_out_78_ap_vld;
reg layer2_out_79_ap_vld;
reg layer2_out_80_ap_vld;
reg layer2_out_81_ap_vld;
reg layer2_out_82_ap_vld;
reg layer2_out_83_ap_vld;
reg layer2_out_84_ap_vld;
reg layer2_out_85_ap_vld;
reg layer2_out_86_ap_vld;
reg layer2_out_87_ap_vld;
reg layer2_out_88_ap_vld;
reg layer2_out_89_ap_vld;
reg layer2_out_90_ap_vld;
reg layer2_out_91_ap_vld;
reg layer2_out_92_ap_vld;
reg layer2_out_93_ap_vld;
reg layer2_out_94_ap_vld;
reg layer2_out_95_ap_vld;
reg layer2_out_96_ap_vld;
reg layer2_out_97_ap_vld;
reg layer2_out_98_ap_vld;
reg layer2_out_99_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    x_in_blk_n;
reg    ap_block_state1;
wire  signed [24:0] sext_ln82_fu_1333_p1;
reg   [24:0] layer2_out_0_preg;
wire   [7:0] mul_ln73_fu_1080_p1;
wire  signed [11:0] data_buf_fu_1126_p1;
wire   [19:0] mul_ln73_fu_1080_p2;
wire   [14:0] trunc_ln_fu_1155_p4;
wire   [11:0] data_buf_3_fu_1130_p4;
wire   [11:0] tmp3_fu_1173_p4;
wire   [13:0] shl_ln_fu_1183_p3;
wire  signed [14:0] sext_ln73_fu_1191_p1;
wire  signed [14:0] sext_ln70_fu_1169_p1;
wire   [14:0] sub_ln73_fu_1195_p2;
wire   [9:0] trunc_ln55_1_fu_1201_p4;
wire   [11:0] data_buf_4_fu_1140_p4;
wire   [11:0] tmp_s_fu_1219_p4;
wire   [15:0] shl_ln73_1_fu_1229_p3;
wire  signed [16:0] sext_ln73_1_fu_1237_p1;
wire  signed [16:0] sext_ln70_1_fu_1215_p1;
wire   [16:0] sub_ln73_1_fu_1241_p2;
wire   [11:0] trunc_ln55_2_fu_1247_p4;
wire   [11:0] tmp_1_fu_1261_p4;
wire   [12:0] shl_ln73_2_fu_1271_p3;
wire  signed [13:0] sext_ln73_2_fu_1279_p1;
wire   [13:0] sub_ln73_2_fu_1283_p2;
wire   [8:0] trunc_ln55_3_fu_1289_p4;
wire  signed [15:0] sext_ln55_fu_1165_p1;
wire  signed [15:0] sext_ln55_1_fu_1257_p1;
wire  signed [10:0] sext_ln70_2_fu_1211_p1;
wire  signed [10:0] sext_ln74_fu_1299_p1;
wire   [10:0] add_ln74_1_fu_1309_p2;
wire  signed [15:0] sext_ln74_1_fu_1315_p1;
wire   [15:0] add_ln74_fu_1303_p2;
wire   [15:0] add_ln74_2_fu_1319_p2;
wire   [20:0] shl_ln1_fu_1325_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 layer2_out_0_preg = 25'd0;
end

model_test_mul_12s_8ns_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 20 ))
mul_12s_8ns_20_1_1_U1(
    .din0(data_buf_fu_1126_p1),
    .din1(mul_ln73_fu_1080_p1),
    .dout(mul_ln73_fu_1080_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                layer2_out_0_preg[5] <= 1'b0;
        layer2_out_0_preg[6] <= 1'b0;
        layer2_out_0_preg[7] <= 1'b0;
        layer2_out_0_preg[8] <= 1'b0;
        layer2_out_0_preg[9] <= 1'b0;
        layer2_out_0_preg[10] <= 1'b0;
        layer2_out_0_preg[11] <= 1'b0;
        layer2_out_0_preg[12] <= 1'b0;
        layer2_out_0_preg[13] <= 1'b0;
        layer2_out_0_preg[14] <= 1'b0;
        layer2_out_0_preg[15] <= 1'b0;
        layer2_out_0_preg[16] <= 1'b0;
        layer2_out_0_preg[17] <= 1'b0;
        layer2_out_0_preg[18] <= 1'b0;
        layer2_out_0_preg[19] <= 1'b0;
        layer2_out_0_preg[20] <= 1'b0;
        layer2_out_0_preg[21] <= 1'b0;
        layer2_out_0_preg[22] <= 1'b0;
        layer2_out_0_preg[23] <= 1'b0;
        layer2_out_0_preg[24] <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                        layer2_out_0_preg[24 : 5] <= sext_ln82_fu_1333_p1[24 : 5];
        end
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_0 = sext_ln82_fu_1333_p1;
    end else begin
        layer2_out_0 = layer2_out_0_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_0_ap_vld = 1'b1;
    end else begin
        layer2_out_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_10_ap_vld = 1'b1;
    end else begin
        layer2_out_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_11_ap_vld = 1'b1;
    end else begin
        layer2_out_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_12_ap_vld = 1'b1;
    end else begin
        layer2_out_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_13_ap_vld = 1'b1;
    end else begin
        layer2_out_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_14_ap_vld = 1'b1;
    end else begin
        layer2_out_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_15_ap_vld = 1'b1;
    end else begin
        layer2_out_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_16_ap_vld = 1'b1;
    end else begin
        layer2_out_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_17_ap_vld = 1'b1;
    end else begin
        layer2_out_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_18_ap_vld = 1'b1;
    end else begin
        layer2_out_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_19_ap_vld = 1'b1;
    end else begin
        layer2_out_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_1_ap_vld = 1'b1;
    end else begin
        layer2_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_20_ap_vld = 1'b1;
    end else begin
        layer2_out_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_21_ap_vld = 1'b1;
    end else begin
        layer2_out_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_22_ap_vld = 1'b1;
    end else begin
        layer2_out_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_23_ap_vld = 1'b1;
    end else begin
        layer2_out_23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_24_ap_vld = 1'b1;
    end else begin
        layer2_out_24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_25_ap_vld = 1'b1;
    end else begin
        layer2_out_25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_26_ap_vld = 1'b1;
    end else begin
        layer2_out_26_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_27_ap_vld = 1'b1;
    end else begin
        layer2_out_27_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_28_ap_vld = 1'b1;
    end else begin
        layer2_out_28_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_29_ap_vld = 1'b1;
    end else begin
        layer2_out_29_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_2_ap_vld = 1'b1;
    end else begin
        layer2_out_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_30_ap_vld = 1'b1;
    end else begin
        layer2_out_30_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_31_ap_vld = 1'b1;
    end else begin
        layer2_out_31_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_32_ap_vld = 1'b1;
    end else begin
        layer2_out_32_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_33_ap_vld = 1'b1;
    end else begin
        layer2_out_33_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_34_ap_vld = 1'b1;
    end else begin
        layer2_out_34_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_35_ap_vld = 1'b1;
    end else begin
        layer2_out_35_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_36_ap_vld = 1'b1;
    end else begin
        layer2_out_36_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_37_ap_vld = 1'b1;
    end else begin
        layer2_out_37_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_38_ap_vld = 1'b1;
    end else begin
        layer2_out_38_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_39_ap_vld = 1'b1;
    end else begin
        layer2_out_39_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_3_ap_vld = 1'b1;
    end else begin
        layer2_out_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_40_ap_vld = 1'b1;
    end else begin
        layer2_out_40_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_41_ap_vld = 1'b1;
    end else begin
        layer2_out_41_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_42_ap_vld = 1'b1;
    end else begin
        layer2_out_42_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_43_ap_vld = 1'b1;
    end else begin
        layer2_out_43_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_44_ap_vld = 1'b1;
    end else begin
        layer2_out_44_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_45_ap_vld = 1'b1;
    end else begin
        layer2_out_45_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_46_ap_vld = 1'b1;
    end else begin
        layer2_out_46_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_47_ap_vld = 1'b1;
    end else begin
        layer2_out_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_48_ap_vld = 1'b1;
    end else begin
        layer2_out_48_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_49_ap_vld = 1'b1;
    end else begin
        layer2_out_49_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_4_ap_vld = 1'b1;
    end else begin
        layer2_out_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_50_ap_vld = 1'b1;
    end else begin
        layer2_out_50_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_51_ap_vld = 1'b1;
    end else begin
        layer2_out_51_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_52_ap_vld = 1'b1;
    end else begin
        layer2_out_52_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_53_ap_vld = 1'b1;
    end else begin
        layer2_out_53_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_54_ap_vld = 1'b1;
    end else begin
        layer2_out_54_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_55_ap_vld = 1'b1;
    end else begin
        layer2_out_55_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_56_ap_vld = 1'b1;
    end else begin
        layer2_out_56_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_57_ap_vld = 1'b1;
    end else begin
        layer2_out_57_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_58_ap_vld = 1'b1;
    end else begin
        layer2_out_58_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_59_ap_vld = 1'b1;
    end else begin
        layer2_out_59_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_5_ap_vld = 1'b1;
    end else begin
        layer2_out_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_60_ap_vld = 1'b1;
    end else begin
        layer2_out_60_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_61_ap_vld = 1'b1;
    end else begin
        layer2_out_61_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_62_ap_vld = 1'b1;
    end else begin
        layer2_out_62_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_63_ap_vld = 1'b1;
    end else begin
        layer2_out_63_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_64_ap_vld = 1'b1;
    end else begin
        layer2_out_64_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_65_ap_vld = 1'b1;
    end else begin
        layer2_out_65_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_66_ap_vld = 1'b1;
    end else begin
        layer2_out_66_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_67_ap_vld = 1'b1;
    end else begin
        layer2_out_67_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_68_ap_vld = 1'b1;
    end else begin
        layer2_out_68_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_69_ap_vld = 1'b1;
    end else begin
        layer2_out_69_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_6_ap_vld = 1'b1;
    end else begin
        layer2_out_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_70_ap_vld = 1'b1;
    end else begin
        layer2_out_70_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_71_ap_vld = 1'b1;
    end else begin
        layer2_out_71_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_72_ap_vld = 1'b1;
    end else begin
        layer2_out_72_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_73_ap_vld = 1'b1;
    end else begin
        layer2_out_73_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_74_ap_vld = 1'b1;
    end else begin
        layer2_out_74_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_75_ap_vld = 1'b1;
    end else begin
        layer2_out_75_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_76_ap_vld = 1'b1;
    end else begin
        layer2_out_76_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_77_ap_vld = 1'b1;
    end else begin
        layer2_out_77_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_78_ap_vld = 1'b1;
    end else begin
        layer2_out_78_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_79_ap_vld = 1'b1;
    end else begin
        layer2_out_79_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_7_ap_vld = 1'b1;
    end else begin
        layer2_out_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_80_ap_vld = 1'b1;
    end else begin
        layer2_out_80_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_81_ap_vld = 1'b1;
    end else begin
        layer2_out_81_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_82_ap_vld = 1'b1;
    end else begin
        layer2_out_82_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_83_ap_vld = 1'b1;
    end else begin
        layer2_out_83_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_84_ap_vld = 1'b1;
    end else begin
        layer2_out_84_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_85_ap_vld = 1'b1;
    end else begin
        layer2_out_85_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_86_ap_vld = 1'b1;
    end else begin
        layer2_out_86_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_87_ap_vld = 1'b1;
    end else begin
        layer2_out_87_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_88_ap_vld = 1'b1;
    end else begin
        layer2_out_88_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_89_ap_vld = 1'b1;
    end else begin
        layer2_out_89_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_8_ap_vld = 1'b1;
    end else begin
        layer2_out_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_90_ap_vld = 1'b1;
    end else begin
        layer2_out_90_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_91_ap_vld = 1'b1;
    end else begin
        layer2_out_91_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_92_ap_vld = 1'b1;
    end else begin
        layer2_out_92_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_93_ap_vld = 1'b1;
    end else begin
        layer2_out_93_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_94_ap_vld = 1'b1;
    end else begin
        layer2_out_94_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_95_ap_vld = 1'b1;
    end else begin
        layer2_out_95_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_96_ap_vld = 1'b1;
    end else begin
        layer2_out_96_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_97_ap_vld = 1'b1;
    end else begin
        layer2_out_97_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_98_ap_vld = 1'b1;
    end else begin
        layer2_out_98_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_99_ap_vld = 1'b1;
    end else begin
        layer2_out_99_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_out_9_ap_vld = 1'b1;
    end else begin
        layer2_out_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_in_blk_n = x_in_ap_vld;
    end else begin
        x_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln74_1_fu_1309_p2 = ($signed(sext_ln70_2_fu_1211_p1) + $signed(sext_ln74_fu_1299_p1));

assign add_ln74_2_fu_1319_p2 = ($signed(sext_ln74_1_fu_1315_p1) + $signed(add_ln74_fu_1303_p2));

assign add_ln74_fu_1303_p2 = ($signed(sext_ln55_fu_1165_p1) + $signed(sext_ln55_1_fu_1257_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (x_in_ap_vld == 1'b0) | (ap_done_reg == 1'b1));
end

assign data_buf_3_fu_1130_p4 = {{x_in[23:12]}};

assign data_buf_4_fu_1140_p4 = {{x_in[131:120]}};

assign data_buf_fu_1126_p1 = x_in[11:0];

assign layer2_out_1 = 25'd0;

assign layer2_out_10 = 25'd0;

assign layer2_out_11 = 25'd0;

assign layer2_out_12 = 25'd0;

assign layer2_out_13 = 25'd0;

assign layer2_out_14 = 25'd0;

assign layer2_out_15 = 25'd0;

assign layer2_out_16 = 25'd0;

assign layer2_out_17 = 25'd0;

assign layer2_out_18 = 25'd0;

assign layer2_out_19 = 25'd0;

assign layer2_out_2 = 25'd0;

assign layer2_out_20 = 25'd0;

assign layer2_out_21 = 25'd0;

assign layer2_out_22 = 25'd0;

assign layer2_out_23 = 25'd0;

assign layer2_out_24 = 25'd0;

assign layer2_out_25 = 25'd0;

assign layer2_out_26 = 25'd0;

assign layer2_out_27 = 25'd0;

assign layer2_out_28 = 25'd0;

assign layer2_out_29 = 25'd0;

assign layer2_out_3 = 25'd0;

assign layer2_out_30 = 25'd0;

assign layer2_out_31 = 25'd0;

assign layer2_out_32 = 25'd0;

assign layer2_out_33 = 25'd0;

assign layer2_out_34 = 25'd0;

assign layer2_out_35 = 25'd0;

assign layer2_out_36 = 25'd0;

assign layer2_out_37 = 25'd0;

assign layer2_out_38 = 25'd0;

assign layer2_out_39 = 25'd0;

assign layer2_out_4 = 25'd0;

assign layer2_out_40 = 25'd0;

assign layer2_out_41 = 25'd0;

assign layer2_out_42 = 25'd0;

assign layer2_out_43 = 25'd0;

assign layer2_out_44 = 25'd0;

assign layer2_out_45 = 25'd0;

assign layer2_out_46 = 25'd0;

assign layer2_out_47 = 25'd0;

assign layer2_out_48 = 25'd0;

assign layer2_out_49 = 25'd0;

assign layer2_out_5 = 25'd0;

assign layer2_out_50 = 25'd0;

assign layer2_out_51 = 25'd0;

assign layer2_out_52 = 25'd0;

assign layer2_out_53 = 25'd0;

assign layer2_out_54 = 25'd0;

assign layer2_out_55 = 25'd0;

assign layer2_out_56 = 25'd0;

assign layer2_out_57 = 25'd0;

assign layer2_out_58 = 25'd0;

assign layer2_out_59 = 25'd0;

assign layer2_out_6 = 25'd0;

assign layer2_out_60 = 25'd0;

assign layer2_out_61 = 25'd0;

assign layer2_out_62 = 25'd0;

assign layer2_out_63 = 25'd0;

assign layer2_out_64 = 25'd0;

assign layer2_out_65 = 25'd0;

assign layer2_out_66 = 25'd0;

assign layer2_out_67 = 25'd0;

assign layer2_out_68 = 25'd0;

assign layer2_out_69 = 25'd0;

assign layer2_out_7 = 25'd0;

assign layer2_out_70 = 25'd0;

assign layer2_out_71 = 25'd0;

assign layer2_out_72 = 25'd0;

assign layer2_out_73 = 25'd0;

assign layer2_out_74 = 25'd0;

assign layer2_out_75 = 25'd0;

assign layer2_out_76 = 25'd0;

assign layer2_out_77 = 25'd0;

assign layer2_out_78 = 25'd0;

assign layer2_out_79 = 25'd0;

assign layer2_out_8 = 25'd0;

assign layer2_out_80 = 25'd0;

assign layer2_out_81 = 25'd0;

assign layer2_out_82 = 25'd0;

assign layer2_out_83 = 25'd0;

assign layer2_out_84 = 25'd0;

assign layer2_out_85 = 25'd0;

assign layer2_out_86 = 25'd0;

assign layer2_out_87 = 25'd0;

assign layer2_out_88 = 25'd0;

assign layer2_out_89 = 25'd0;

assign layer2_out_9 = 25'd0;

assign layer2_out_90 = 25'd0;

assign layer2_out_91 = 25'd0;

assign layer2_out_92 = 25'd0;

assign layer2_out_93 = 25'd0;

assign layer2_out_94 = 25'd0;

assign layer2_out_95 = 25'd0;

assign layer2_out_96 = 25'd0;

assign layer2_out_97 = 25'd0;

assign layer2_out_98 = 25'd0;

assign layer2_out_99 = 25'd0;

assign mul_ln73_fu_1080_p1 = 20'd90;

assign sext_ln55_1_fu_1257_p1 = $signed(trunc_ln55_2_fu_1247_p4);

assign sext_ln55_fu_1165_p1 = $signed(trunc_ln_fu_1155_p4);

assign sext_ln70_1_fu_1215_p1 = $signed(data_buf_4_fu_1140_p4);

assign sext_ln70_2_fu_1211_p1 = $signed(trunc_ln55_1_fu_1201_p4);

assign sext_ln70_fu_1169_p1 = $signed(data_buf_3_fu_1130_p4);

assign sext_ln73_1_fu_1237_p1 = $signed(shl_ln73_1_fu_1229_p3);

assign sext_ln73_2_fu_1279_p1 = $signed(shl_ln73_2_fu_1271_p3);

assign sext_ln73_fu_1191_p1 = $signed(shl_ln_fu_1183_p3);

assign sext_ln74_1_fu_1315_p1 = $signed(add_ln74_1_fu_1309_p2);

assign sext_ln74_fu_1299_p1 = $signed(trunc_ln55_3_fu_1289_p4);

assign sext_ln82_fu_1333_p1 = $signed(shl_ln1_fu_1325_p3);

assign shl_ln1_fu_1325_p3 = {{add_ln74_2_fu_1319_p2}, {5'd0}};

assign shl_ln73_1_fu_1229_p3 = {{tmp_s_fu_1219_p4}, {4'd0}};

assign shl_ln73_2_fu_1271_p3 = {{tmp_1_fu_1261_p4}, {1'd0}};

assign shl_ln_fu_1183_p3 = {{tmp3_fu_1173_p4}, {2'd0}};

assign sub_ln73_1_fu_1241_p2 = ($signed(sext_ln73_1_fu_1237_p1) - $signed(sext_ln70_1_fu_1215_p1));

assign sub_ln73_2_fu_1283_p2 = ($signed(14'd0) - $signed(sext_ln73_2_fu_1279_p1));

assign sub_ln73_fu_1195_p2 = ($signed(sext_ln73_fu_1191_p1) - $signed(sext_ln70_fu_1169_p1));

assign tmp3_fu_1173_p4 = {{x_in[23:12]}};

assign tmp_1_fu_1261_p4 = {{x_in[143:132]}};

assign tmp_s_fu_1219_p4 = {{x_in[131:120]}};

assign trunc_ln55_1_fu_1201_p4 = {{sub_ln73_fu_1195_p2[14:5]}};

assign trunc_ln55_2_fu_1247_p4 = {{sub_ln73_1_fu_1241_p2[16:5]}};

assign trunc_ln55_3_fu_1289_p4 = {{sub_ln73_2_fu_1283_p2[13:5]}};

assign trunc_ln_fu_1155_p4 = {{mul_ln73_fu_1080_p2[19:5]}};

always @ (posedge ap_clk) begin
    layer2_out_0_preg[4:0] <= 5'b00000;
end

endmodule //model_test_conv_2d_cl_ap_fixed_12_4_0_0_0_ap_fixed_25_10_5_3_0_config2_s
