// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pool_op_ap_fixed_20_11_4_0_0_16_1_ap_fixed_16_6_5_3_0_s (
        ap_ready,
        x_0_V_read,
        x_1_V_read,
        x_2_V_read,
        x_3_V_read,
        x_4_V_read,
        x_5_V_read,
        x_6_V_read,
        x_7_V_read,
        x_8_V_read,
        x_9_V_read,
        x_10_V_read,
        x_11_V_read,
        x_12_V_read,
        x_13_V_read,
        x_14_V_read,
        x_15_V_read,
        ap_return
);


output   ap_ready;
input  [8:0] x_0_V_read;
input  [8:0] x_1_V_read;
input  [8:0] x_2_V_read;
input  [8:0] x_3_V_read;
input  [8:0] x_4_V_read;
input  [8:0] x_5_V_read;
input  [8:0] x_6_V_read;
input  [8:0] x_7_V_read;
input  [8:0] x_8_V_read;
input  [8:0] x_9_V_read;
input  [8:0] x_10_V_read;
input  [8:0] x_11_V_read;
input  [8:0] x_12_V_read;
input  [8:0] x_13_V_read;
input  [8:0] x_14_V_read;
input  [8:0] x_15_V_read;
output  [9:0] ap_return;

wire   [9:0] shl_ln_fu_140_p3;
wire   [9:0] shl_ln703_1_fu_152_p3;
wire   [9:0] shl_ln703_2_fu_164_p3;
wire   [9:0] shl_ln703_3_fu_176_p3;
wire   [9:0] shl_ln703_4_fu_188_p3;
wire   [9:0] shl_ln703_5_fu_200_p3;
wire   [9:0] shl_ln703_6_fu_212_p3;
wire   [9:0] shl_ln703_7_fu_224_p3;
wire   [9:0] shl_ln703_8_fu_236_p3;
wire   [9:0] shl_ln703_9_fu_248_p3;
wire   [9:0] shl_ln703_s_fu_260_p3;
wire   [9:0] shl_ln703_10_fu_272_p3;
wire   [9:0] shl_ln703_11_fu_284_p3;
wire   [9:0] shl_ln703_12_fu_296_p3;
wire   [9:0] shl_ln703_13_fu_308_p3;
wire   [9:0] shl_ln703_14_fu_320_p3;
wire   [10:0] zext_ln703_1_fu_160_p1;
wire   [10:0] zext_ln703_fu_148_p1;
wire   [10:0] add_ln703_fu_332_p2;
wire   [10:0] zext_ln703_3_fu_184_p1;
wire   [10:0] zext_ln703_2_fu_172_p1;
wire   [10:0] add_ln703_1_fu_342_p2;
wire   [11:0] zext_ln703_16_fu_338_p1;
wire   [11:0] zext_ln703_17_fu_348_p1;
wire   [11:0] add_ln703_2_fu_352_p2;
wire   [10:0] zext_ln703_5_fu_208_p1;
wire   [10:0] zext_ln703_4_fu_196_p1;
wire   [10:0] add_ln703_3_fu_362_p2;
wire   [10:0] zext_ln703_7_fu_232_p1;
wire   [10:0] zext_ln703_6_fu_220_p1;
wire   [10:0] add_ln703_4_fu_372_p2;
wire   [11:0] zext_ln703_19_fu_368_p1;
wire   [11:0] zext_ln703_20_fu_378_p1;
wire   [11:0] add_ln703_5_fu_382_p2;
wire   [12:0] zext_ln703_18_fu_358_p1;
wire   [12:0] zext_ln703_21_fu_388_p1;
wire   [12:0] add_ln703_6_fu_392_p2;
wire   [10:0] zext_ln703_9_fu_256_p1;
wire   [10:0] zext_ln703_8_fu_244_p1;
wire   [10:0] add_ln703_7_fu_402_p2;
wire   [10:0] zext_ln703_11_fu_280_p1;
wire   [10:0] zext_ln703_10_fu_268_p1;
wire   [10:0] add_ln703_8_fu_412_p2;
wire   [11:0] zext_ln703_23_fu_408_p1;
wire   [11:0] zext_ln703_24_fu_418_p1;
wire   [11:0] add_ln703_9_fu_422_p2;
wire   [10:0] zext_ln703_13_fu_304_p1;
wire   [10:0] zext_ln703_12_fu_292_p1;
wire   [10:0] add_ln703_10_fu_432_p2;
wire   [10:0] zext_ln703_15_fu_328_p1;
wire   [10:0] zext_ln703_14_fu_316_p1;
wire   [10:0] add_ln703_11_fu_442_p2;
wire   [11:0] zext_ln703_26_fu_438_p1;
wire   [11:0] zext_ln703_27_fu_448_p1;
wire   [11:0] add_ln703_12_fu_452_p2;
wire   [12:0] zext_ln703_25_fu_428_p1;
wire   [12:0] zext_ln703_28_fu_458_p1;
wire   [12:0] add_ln703_13_fu_462_p2;
wire   [13:0] zext_ln703_22_fu_398_p1;
wire   [13:0] zext_ln703_29_fu_468_p1;
wire   [13:0] add_ln703_14_fu_472_p2;

assign add_ln703_10_fu_432_p2 = (zext_ln703_13_fu_304_p1 + zext_ln703_12_fu_292_p1);

assign add_ln703_11_fu_442_p2 = (zext_ln703_15_fu_328_p1 + zext_ln703_14_fu_316_p1);

assign add_ln703_12_fu_452_p2 = (zext_ln703_26_fu_438_p1 + zext_ln703_27_fu_448_p1);

assign add_ln703_13_fu_462_p2 = (zext_ln703_25_fu_428_p1 + zext_ln703_28_fu_458_p1);

assign add_ln703_14_fu_472_p2 = (zext_ln703_22_fu_398_p1 + zext_ln703_29_fu_468_p1);

assign add_ln703_1_fu_342_p2 = (zext_ln703_3_fu_184_p1 + zext_ln703_2_fu_172_p1);

assign add_ln703_2_fu_352_p2 = (zext_ln703_16_fu_338_p1 + zext_ln703_17_fu_348_p1);

assign add_ln703_3_fu_362_p2 = (zext_ln703_5_fu_208_p1 + zext_ln703_4_fu_196_p1);

assign add_ln703_4_fu_372_p2 = (zext_ln703_7_fu_232_p1 + zext_ln703_6_fu_220_p1);

assign add_ln703_5_fu_382_p2 = (zext_ln703_19_fu_368_p1 + zext_ln703_20_fu_378_p1);

assign add_ln703_6_fu_392_p2 = (zext_ln703_18_fu_358_p1 + zext_ln703_21_fu_388_p1);

assign add_ln703_7_fu_402_p2 = (zext_ln703_9_fu_256_p1 + zext_ln703_8_fu_244_p1);

assign add_ln703_8_fu_412_p2 = (zext_ln703_11_fu_280_p1 + zext_ln703_10_fu_268_p1);

assign add_ln703_9_fu_422_p2 = (zext_ln703_23_fu_408_p1 + zext_ln703_24_fu_418_p1);

assign add_ln703_fu_332_p2 = (zext_ln703_1_fu_160_p1 + zext_ln703_fu_148_p1);

assign ap_ready = 1'b1;

assign ap_return = {{add_ln703_14_fu_472_p2[13:4]}};

assign shl_ln703_10_fu_272_p3 = {{x_11_V_read}, {1'd0}};

assign shl_ln703_11_fu_284_p3 = {{x_12_V_read}, {1'd0}};

assign shl_ln703_12_fu_296_p3 = {{x_13_V_read}, {1'd0}};

assign shl_ln703_13_fu_308_p3 = {{x_14_V_read}, {1'd0}};

assign shl_ln703_14_fu_320_p3 = {{x_15_V_read}, {1'd0}};

assign shl_ln703_1_fu_152_p3 = {{x_1_V_read}, {1'd0}};

assign shl_ln703_2_fu_164_p3 = {{x_2_V_read}, {1'd0}};

assign shl_ln703_3_fu_176_p3 = {{x_3_V_read}, {1'd0}};

assign shl_ln703_4_fu_188_p3 = {{x_4_V_read}, {1'd0}};

assign shl_ln703_5_fu_200_p3 = {{x_5_V_read}, {1'd0}};

assign shl_ln703_6_fu_212_p3 = {{x_6_V_read}, {1'd0}};

assign shl_ln703_7_fu_224_p3 = {{x_7_V_read}, {1'd0}};

assign shl_ln703_8_fu_236_p3 = {{x_8_V_read}, {1'd0}};

assign shl_ln703_9_fu_248_p3 = {{x_9_V_read}, {1'd0}};

assign shl_ln703_s_fu_260_p3 = {{x_10_V_read}, {1'd0}};

assign shl_ln_fu_140_p3 = {{x_0_V_read}, {1'd0}};

assign zext_ln703_10_fu_268_p1 = shl_ln703_s_fu_260_p3;

assign zext_ln703_11_fu_280_p1 = shl_ln703_10_fu_272_p3;

assign zext_ln703_12_fu_292_p1 = shl_ln703_11_fu_284_p3;

assign zext_ln703_13_fu_304_p1 = shl_ln703_12_fu_296_p3;

assign zext_ln703_14_fu_316_p1 = shl_ln703_13_fu_308_p3;

assign zext_ln703_15_fu_328_p1 = shl_ln703_14_fu_320_p3;

assign zext_ln703_16_fu_338_p1 = add_ln703_fu_332_p2;

assign zext_ln703_17_fu_348_p1 = add_ln703_1_fu_342_p2;

assign zext_ln703_18_fu_358_p1 = add_ln703_2_fu_352_p2;

assign zext_ln703_19_fu_368_p1 = add_ln703_3_fu_362_p2;

assign zext_ln703_1_fu_160_p1 = shl_ln703_1_fu_152_p3;

assign zext_ln703_20_fu_378_p1 = add_ln703_4_fu_372_p2;

assign zext_ln703_21_fu_388_p1 = add_ln703_5_fu_382_p2;

assign zext_ln703_22_fu_398_p1 = add_ln703_6_fu_392_p2;

assign zext_ln703_23_fu_408_p1 = add_ln703_7_fu_402_p2;

assign zext_ln703_24_fu_418_p1 = add_ln703_8_fu_412_p2;

assign zext_ln703_25_fu_428_p1 = add_ln703_9_fu_422_p2;

assign zext_ln703_26_fu_438_p1 = add_ln703_10_fu_432_p2;

assign zext_ln703_27_fu_448_p1 = add_ln703_11_fu_442_p2;

assign zext_ln703_28_fu_458_p1 = add_ln703_12_fu_452_p2;

assign zext_ln703_29_fu_468_p1 = add_ln703_13_fu_462_p2;

assign zext_ln703_2_fu_172_p1 = shl_ln703_2_fu_164_p3;

assign zext_ln703_3_fu_184_p1 = shl_ln703_3_fu_176_p3;

assign zext_ln703_4_fu_196_p1 = shl_ln703_4_fu_188_p3;

assign zext_ln703_5_fu_208_p1 = shl_ln703_5_fu_200_p3;

assign zext_ln703_6_fu_220_p1 = shl_ln703_6_fu_212_p3;

assign zext_ln703_7_fu_232_p1 = shl_ln703_7_fu_224_p3;

assign zext_ln703_8_fu_244_p1 = shl_ln703_8_fu_236_p3;

assign zext_ln703_9_fu_256_p1 = shl_ln703_9_fu_248_p3;

assign zext_ln703_fu_148_p1 = shl_ln_fu_140_p3;

endmodule //pool_op_ap_fixed_20_11_4_0_0_16_1_ap_fixed_16_6_5_3_0_s
