Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  LayerName:
    conv1:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 10
      Precision:
        accum: auto
        bias: fixed<6,1,TRN,WRAP,0>
        result: auto
        weight: fixed<6,1,TRN,WRAP,0>
      ReuseFactor: 1
      Trace: false
    conv1_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    dense1:
      Precision:
        accum: auto
        bias: fixed<6,1,TRN,WRAP,0>
        result: auto
        weight: fixed<6,1,TRN,WRAP,0>
      ReuseFactor: 1
      Trace: false
    dense1_linear:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    flatten:
      Precision:
        result: auto
      Trace: false
    pool1:
      ConvImplementation: LineBuffer
      Precision:
        accum: auto
        result: auto
      ReuseFactor: 1
      Trace: false
    relu1:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    x_in:
      Precision:
        result: auto
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_test/keras_model.keras'
OutputDir: model_test
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: model_test
Stamp: 7e03722e
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
