Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    fc1:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    fc1_input:
      Precision:
        result: auto
      Trace: false
    fc1_linear:
      Precision:
        result: auto
      Trace: false
    fc2:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    fc2_linear:
      Precision:
        result: auto
      Trace: false
    fc3:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    fc3_linear:
      Precision:
        result: auto
      Trace: false
    output:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    output_linear:
      Precision:
        result: auto
      Trace: false
    relu1:
      Precision:
        result: auto
      Trace: false
    relu2:
      Precision:
        result: auto
      Trace: false
    relu3:
      Precision:
        result: auto
      Trace: false
    softmax:
      Precision:
        result: auto
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls_test/keras_model.keras'
OutputDir: hls_test
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: hls_test
Stamp: 5c4dc088
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
