// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pointwise_conv_1d_cl_array_array_ap_fixed_23_8_5_3_0_32u_config19_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_data_0_V_TDATA,
        data_V_data_0_V_TVALID,
        data_V_data_0_V_TREADY,
        data_V_data_1_V_TDATA,
        data_V_data_1_V_TVALID,
        data_V_data_1_V_TREADY,
        data_V_data_2_V_TDATA,
        data_V_data_2_V_TVALID,
        data_V_data_2_V_TREADY,
        res_V_data_0_V_din,
        res_V_data_0_V_full_n,
        res_V_data_0_V_write,
        res_V_data_1_V_din,
        res_V_data_1_V_full_n,
        res_V_data_1_V_write,
        res_V_data_2_V_din,
        res_V_data_2_V_full_n,
        res_V_data_2_V_write,
        res_V_data_3_V_din,
        res_V_data_3_V_full_n,
        res_V_data_3_V_write,
        res_V_data_4_V_din,
        res_V_data_4_V_full_n,
        res_V_data_4_V_write,
        res_V_data_5_V_din,
        res_V_data_5_V_full_n,
        res_V_data_5_V_write,
        res_V_data_6_V_din,
        res_V_data_6_V_full_n,
        res_V_data_6_V_write,
        res_V_data_7_V_din,
        res_V_data_7_V_full_n,
        res_V_data_7_V_write,
        res_V_data_8_V_din,
        res_V_data_8_V_full_n,
        res_V_data_8_V_write,
        res_V_data_9_V_din,
        res_V_data_9_V_full_n,
        res_V_data_9_V_write,
        res_V_data_10_V_din,
        res_V_data_10_V_full_n,
        res_V_data_10_V_write,
        res_V_data_11_V_din,
        res_V_data_11_V_full_n,
        res_V_data_11_V_write,
        res_V_data_12_V_din,
        res_V_data_12_V_full_n,
        res_V_data_12_V_write,
        res_V_data_13_V_din,
        res_V_data_13_V_full_n,
        res_V_data_13_V_write,
        res_V_data_14_V_din,
        res_V_data_14_V_full_n,
        res_V_data_14_V_write,
        res_V_data_15_V_din,
        res_V_data_15_V_full_n,
        res_V_data_15_V_write,
        res_V_data_16_V_din,
        res_V_data_16_V_full_n,
        res_V_data_16_V_write,
        res_V_data_17_V_din,
        res_V_data_17_V_full_n,
        res_V_data_17_V_write,
        res_V_data_18_V_din,
        res_V_data_18_V_full_n,
        res_V_data_18_V_write,
        res_V_data_19_V_din,
        res_V_data_19_V_full_n,
        res_V_data_19_V_write,
        res_V_data_20_V_din,
        res_V_data_20_V_full_n,
        res_V_data_20_V_write,
        res_V_data_21_V_din,
        res_V_data_21_V_full_n,
        res_V_data_21_V_write,
        res_V_data_22_V_din,
        res_V_data_22_V_full_n,
        res_V_data_22_V_write,
        res_V_data_23_V_din,
        res_V_data_23_V_full_n,
        res_V_data_23_V_write,
        res_V_data_24_V_din,
        res_V_data_24_V_full_n,
        res_V_data_24_V_write,
        res_V_data_25_V_din,
        res_V_data_25_V_full_n,
        res_V_data_25_V_write,
        res_V_data_26_V_din,
        res_V_data_26_V_full_n,
        res_V_data_26_V_write,
        res_V_data_27_V_din,
        res_V_data_27_V_full_n,
        res_V_data_27_V_write,
        res_V_data_28_V_din,
        res_V_data_28_V_full_n,
        res_V_data_28_V_write,
        res_V_data_29_V_din,
        res_V_data_29_V_full_n,
        res_V_data_29_V_write,
        res_V_data_30_V_din,
        res_V_data_30_V_full_n,
        res_V_data_30_V_write,
        res_V_data_31_V_din,
        res_V_data_31_V_full_n,
        res_V_data_31_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] data_V_data_0_V_TDATA;
input   data_V_data_0_V_TVALID;
output   data_V_data_0_V_TREADY;
input  [15:0] data_V_data_1_V_TDATA;
input   data_V_data_1_V_TVALID;
output   data_V_data_1_V_TREADY;
input  [15:0] data_V_data_2_V_TDATA;
input   data_V_data_2_V_TVALID;
output   data_V_data_2_V_TREADY;
output  [22:0] res_V_data_0_V_din;
input   res_V_data_0_V_full_n;
output   res_V_data_0_V_write;
output  [22:0] res_V_data_1_V_din;
input   res_V_data_1_V_full_n;
output   res_V_data_1_V_write;
output  [22:0] res_V_data_2_V_din;
input   res_V_data_2_V_full_n;
output   res_V_data_2_V_write;
output  [22:0] res_V_data_3_V_din;
input   res_V_data_3_V_full_n;
output   res_V_data_3_V_write;
output  [22:0] res_V_data_4_V_din;
input   res_V_data_4_V_full_n;
output   res_V_data_4_V_write;
output  [22:0] res_V_data_5_V_din;
input   res_V_data_5_V_full_n;
output   res_V_data_5_V_write;
output  [22:0] res_V_data_6_V_din;
input   res_V_data_6_V_full_n;
output   res_V_data_6_V_write;
output  [22:0] res_V_data_7_V_din;
input   res_V_data_7_V_full_n;
output   res_V_data_7_V_write;
output  [22:0] res_V_data_8_V_din;
input   res_V_data_8_V_full_n;
output   res_V_data_8_V_write;
output  [22:0] res_V_data_9_V_din;
input   res_V_data_9_V_full_n;
output   res_V_data_9_V_write;
output  [22:0] res_V_data_10_V_din;
input   res_V_data_10_V_full_n;
output   res_V_data_10_V_write;
output  [22:0] res_V_data_11_V_din;
input   res_V_data_11_V_full_n;
output   res_V_data_11_V_write;
output  [22:0] res_V_data_12_V_din;
input   res_V_data_12_V_full_n;
output   res_V_data_12_V_write;
output  [22:0] res_V_data_13_V_din;
input   res_V_data_13_V_full_n;
output   res_V_data_13_V_write;
output  [22:0] res_V_data_14_V_din;
input   res_V_data_14_V_full_n;
output   res_V_data_14_V_write;
output  [22:0] res_V_data_15_V_din;
input   res_V_data_15_V_full_n;
output   res_V_data_15_V_write;
output  [22:0] res_V_data_16_V_din;
input   res_V_data_16_V_full_n;
output   res_V_data_16_V_write;
output  [22:0] res_V_data_17_V_din;
input   res_V_data_17_V_full_n;
output   res_V_data_17_V_write;
output  [22:0] res_V_data_18_V_din;
input   res_V_data_18_V_full_n;
output   res_V_data_18_V_write;
output  [22:0] res_V_data_19_V_din;
input   res_V_data_19_V_full_n;
output   res_V_data_19_V_write;
output  [22:0] res_V_data_20_V_din;
input   res_V_data_20_V_full_n;
output   res_V_data_20_V_write;
output  [22:0] res_V_data_21_V_din;
input   res_V_data_21_V_full_n;
output   res_V_data_21_V_write;
output  [22:0] res_V_data_22_V_din;
input   res_V_data_22_V_full_n;
output   res_V_data_22_V_write;
output  [22:0] res_V_data_23_V_din;
input   res_V_data_23_V_full_n;
output   res_V_data_23_V_write;
output  [22:0] res_V_data_24_V_din;
input   res_V_data_24_V_full_n;
output   res_V_data_24_V_write;
output  [22:0] res_V_data_25_V_din;
input   res_V_data_25_V_full_n;
output   res_V_data_25_V_write;
output  [22:0] res_V_data_26_V_din;
input   res_V_data_26_V_full_n;
output   res_V_data_26_V_write;
output  [22:0] res_V_data_27_V_din;
input   res_V_data_27_V_full_n;
output   res_V_data_27_V_write;
output  [22:0] res_V_data_28_V_din;
input   res_V_data_28_V_full_n;
output   res_V_data_28_V_write;
output  [22:0] res_V_data_29_V_din;
input   res_V_data_29_V_full_n;
output   res_V_data_29_V_write;
output  [22:0] res_V_data_30_V_din;
input   res_V_data_30_V_full_n;
output   res_V_data_30_V_write;
output  [22:0] res_V_data_31_V_din;
input   res_V_data_31_V_full_n;
output   res_V_data_31_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_data_0_V_TREADY;
reg data_V_data_1_V_TREADY;
reg data_V_data_2_V_TREADY;
reg res_V_data_0_V_write;
reg res_V_data_1_V_write;
reg res_V_data_2_V_write;
reg res_V_data_3_V_write;
reg res_V_data_4_V_write;
reg res_V_data_5_V_write;
reg res_V_data_6_V_write;
reg res_V_data_7_V_write;
reg res_V_data_8_V_write;
reg res_V_data_9_V_write;
reg res_V_data_10_V_write;
reg res_V_data_11_V_write;
reg res_V_data_12_V_write;
reg res_V_data_13_V_write;
reg res_V_data_14_V_write;
reg res_V_data_15_V_write;
reg res_V_data_16_V_write;
reg res_V_data_17_V_write;
reg res_V_data_18_V_write;
reg res_V_data_19_V_write;
reg res_V_data_20_V_write;
reg res_V_data_21_V_write;
reg res_V_data_22_V_write;
reg res_V_data_23_V_write;
reg res_V_data_24_V_write;
reg res_V_data_25_V_write;
reg res_V_data_26_V_write;
reg res_V_data_27_V_write;
reg res_V_data_28_V_write;
reg res_V_data_29_V_write;
reg res_V_data_30_V_write;
reg res_V_data_31_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    data_V_data_0_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln89_fu_6920_p2;
reg    data_V_data_1_V_TDATA_blk_n;
reg    data_V_data_2_V_TDATA_blk_n;
reg    res_V_data_0_V_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln89_reg_9294;
reg    res_V_data_1_V_blk_n;
reg    res_V_data_2_V_blk_n;
reg    res_V_data_3_V_blk_n;
reg    res_V_data_4_V_blk_n;
reg    res_V_data_5_V_blk_n;
reg    res_V_data_6_V_blk_n;
reg    res_V_data_7_V_blk_n;
reg    res_V_data_8_V_blk_n;
reg    res_V_data_9_V_blk_n;
reg    res_V_data_10_V_blk_n;
reg    res_V_data_11_V_blk_n;
reg    res_V_data_12_V_blk_n;
reg    res_V_data_13_V_blk_n;
reg    res_V_data_14_V_blk_n;
reg    res_V_data_15_V_blk_n;
reg    res_V_data_16_V_blk_n;
reg    res_V_data_17_V_blk_n;
reg    res_V_data_18_V_blk_n;
reg    res_V_data_19_V_blk_n;
reg    res_V_data_20_V_blk_n;
reg    res_V_data_21_V_blk_n;
reg    res_V_data_22_V_blk_n;
reg    res_V_data_23_V_blk_n;
reg    res_V_data_24_V_blk_n;
reg    res_V_data_25_V_blk_n;
reg    res_V_data_26_V_blk_n;
reg    res_V_data_27_V_blk_n;
reg    res_V_data_28_V_blk_n;
reg    res_V_data_29_V_blk_n;
reg    res_V_data_30_V_blk_n;
reg    res_V_data_31_V_blk_n;
reg   [4:0] i_iw_0_reg_776;
wire    io_acc_block_signal_op46;
reg    ap_block_state2_pp0_stage0_iter0;
wire    io_acc_block_signal_op465;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] i_iw_fu_6926_p2;
reg   [15:0] tmp_data_0_V_cast_reg_9303;
wire  signed [11:0] tmp_data_2_V_fu_6944_p1;
reg  signed [11:0] tmp_data_2_V_reg_9308;
wire  signed [11:0] tmp_data_1_V_fu_6948_p1;
reg  signed [11:0] tmp_data_1_V_reg_9322;
wire  signed [11:0] tmp_data_0_V_fu_6952_p1;
reg  signed [11:0] tmp_data_0_V_reg_9332;
reg  signed [8:0] trunc_ln708_91_reg_9345;
reg   [12:0] trunc_ln708_92_reg_9351;
reg   [12:0] trunc_ln708_95_reg_9356;
reg   [13:0] trunc_ln708_98_reg_9361;
reg   [7:0] trunc_ln708_101_reg_9366;
reg   [13:0] trunc_ln708_103_reg_9371;
reg   [9:0] trunc_ln708_108_reg_9376;
reg   [7:0] trunc_ln708_114_reg_9381;
reg   [9:0] trunc_ln708_116_reg_9386;
reg   [11:0] trunc_ln708_121_reg_9391;
reg   [11:0] trunc_ln708_123_reg_9396;
wire  signed [19:0] sext_ln1116_2_fu_7138_p1;
reg  signed [19:0] sext_ln1116_2_reg_9401;
reg   [14:0] trunc_ln708_141_reg_9412;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire  signed [11:0] mul_ln1118_9_fu_792_p1;
wire  signed [19:0] sext_ln1116_1_fu_7522_p1;
wire  signed [11:0] mul_ln1118_8_fu_801_p1;
wire  signed [11:0] mul_ln1118_16_fu_804_p1;
wire  signed [11:0] mul_ln1118_11_fu_807_p1;
wire  signed [11:0] mul_ln1118_10_fu_809_p1;
wire  signed [11:0] mul_ln1118_fu_819_p1;
wire  signed [17:0] sext_ln1118_fu_6956_p1;
wire  signed [11:0] mul_ln1118_7_fu_823_p1;
wire  signed [18:0] sext_ln1118_3_fu_6962_p1;
wire  signed [11:0] mul_ln1118_17_fu_828_p1;
wire  signed [11:0] mul_ln1118_6_fu_829_p1;
wire  signed [11:0] mul_ln1118_12_fu_832_p1;
wire  signed [11:0] mul_ln1118_15_fu_845_p1;
wire  signed [11:0] mul_ln1118_13_fu_854_p1;
wire  signed [11:0] mul_ln1118_14_fu_858_p1;
wire  signed [11:0] mul_ln1118_5_fu_862_p1;
wire  signed [11:0] mul_ln1118_19_fu_863_p1;
wire  signed [11:0] mul_ln1118_18_fu_878_p1;
wire   [17:0] mul_ln1118_fu_819_p2;
wire   [17:0] mul_ln1118_5_fu_862_p2;
wire   [18:0] mul_ln1118_6_fu_829_p2;
wire   [18:0] mul_ln1118_7_fu_823_p2;
wire  signed [13:0] shl_ln1118_7_fu_7032_p3;
wire  signed [14:0] sext_ln1118_33_fu_7044_p1;
wire   [14:0] sub_ln1118_7_fu_7048_p2;
wire  signed [14:0] sext_ln1118_30_fu_7028_p1;
wire   [14:0] sub_ln1118_10_fu_7074_p2;
wire   [15:0] shl_ln1118_5_fu_7090_p2;
wire  signed [16:0] sext_ln1118_40_fu_7096_p1;
wire   [16:0] sub_ln1118_14_fu_7100_p2;
wire  signed [16:0] sext_ln1118_32_fu_7040_p1;
wire   [16:0] sub_ln1118_15_fu_7106_p2;
wire   [16:0] sub_ln1118_17_fu_7122_p2;
wire   [19:0] mul_ln1118_19_fu_863_p2;
wire   [18:0] shl_ln_fu_7162_p3;
wire  signed [19:0] sext_ln1118_4_fu_7169_p1;
wire   [19:0] sub_ln1118_fu_7173_p2;
wire   [14:0] trunc_ln_fu_7179_p4;
wire  signed [13:0] shl_ln1118_s_fu_7193_p3;
wire  signed [14:0] sext_ln1118_7_fu_7208_p1;
wire  signed [14:0] sext_ln1118_2_fu_7159_p1;
wire   [14:0] sub_ln1118_1_fu_7212_p2;
wire   [9:0] trunc_ln708_s_fu_7218_p4;
wire  signed [12:0] shl_ln1118_1_fu_7241_p3;
wire  signed [19:0] sext_ln1118_14_fu_7260_p1;
wire   [19:0] sub_ln1118_2_fu_7264_p2;
wire   [14:0] trunc_ln708_93_fu_7270_p4;
wire   [16:0] shl_ln1118_2_fu_7284_p3;
wire  signed [14:0] shl_ln1118_3_fu_7295_p3;
wire  signed [17:0] sext_ln1118_15_fu_7291_p1;
wire  signed [17:0] sext_ln1118_16_fu_7302_p1;
wire   [17:0] add_ln1118_fu_7310_p2;
wire   [12:0] trunc_ln708_94_fu_7316_p4;
wire   [17:0] shl_ln1118_4_fu_7333_p3;
wire  signed [18:0] sext_ln1118_20_fu_7340_p1;
wire  signed [18:0] sext_ln1118_5_fu_7200_p1;
wire   [18:0] add_ln1118_1_fu_7344_p2;
wire   [13:0] trunc_ln708_96_fu_7350_p4;
wire  signed [19:0] sext_ln1116_fu_7153_p1;
wire   [19:0] sub_ln1118_3_fu_7364_p2;
wire   [14:0] trunc_ln708_97_fu_7370_p4;
wire  signed [17:0] sext_ln1118_6_fu_7204_p1;
wire   [17:0] add_ln1118_2_fu_7387_p2;
wire   [12:0] trunc_ln708_99_fu_7393_p4;
wire   [15:0] shl_ln1118_fu_7407_p2;
wire  signed [16:0] sext_ln1118_24_fu_7412_p1;
wire  signed [16:0] sext_ln1118_11_fu_7248_p1;
wire   [16:0] add_ln1118_3_fu_7416_p2;
wire   [11:0] trunc_ln708_100_fu_7422_p4;
wire  signed [15:0] sext_ln1118_17_fu_7306_p1;
wire  signed [15:0] sext_ln1118_12_fu_7252_p1;
wire   [15:0] add_ln1118_4_fu_7439_p2;
wire   [10:0] trunc_ln708_102_fu_7445_p4;
wire  signed [17:0] sext_ln1118_13_fu_7256_p1;
wire   [17:0] add_ln1118_5_fu_7462_p2;
wire   [12:0] trunc_ln708_104_fu_7468_p4;
wire   [17:0] sub_ln1118_4_fu_7482_p2;
wire   [12:0] trunc_ln708_105_fu_7488_p4;
wire  signed [12:0] sext_ln1118_1_fu_7156_p1;
wire   [12:0] sub_ln1118_5_fu_7502_p2;
wire   [7:0] trunc_ln708_106_fu_7508_p4;
wire   [18:0] shl_ln1118_6_fu_7533_p3;
wire  signed [19:0] sext_ln1118_31_fu_7540_p1;
wire   [19:0] sub_ln1118_6_fu_7544_p2;
wire   [14:0] trunc_ln708_107_fu_7550_p4;
wire   [19:0] sub_ln1118_8_fu_7567_p2;
wire   [14:0] trunc_ln708_109_fu_7573_p4;
wire   [19:0] mul_ln1118_8_fu_801_p2;
wire   [14:0] trunc_ln708_110_fu_7587_p4;
wire   [17:0] shl_ln1118_8_fu_7601_p3;
wire  signed [18:0] sext_ln1118_35_fu_7608_p1;
wire   [18:0] sub_ln1118_9_fu_7612_p2;
wire   [13:0] trunc_ln708_111_fu_7618_p4;
wire   [19:0] mul_ln1118_9_fu_792_p2;
wire   [14:0] trunc_ln708_112_fu_7632_p4;
wire   [19:0] mul_ln1118_10_fu_809_p2;
wire   [14:0] trunc_ln708_113_fu_7646_p4;
wire   [19:0] mul_ln1118_11_fu_807_p2;
wire   [14:0] trunc_ln708_115_fu_7663_p4;
wire   [19:0] mul_ln1118_12_fu_832_p2;
wire   [14:0] trunc_ln708_117_fu_7680_p4;
wire   [12:0] shl_ln1118_9_fu_7694_p3;
wire  signed [19:0] sext_ln1118_38_fu_7701_p1;
wire   [19:0] sub_ln1118_11_fu_7705_p2;
wire   [14:0] trunc_ln708_118_fu_7711_p4;
wire   [14:0] tmp_17_fu_7725_p3;
wire  signed [15:0] sext_ln1118_29_fu_7530_p1;
wire  signed [15:0] sext_ln1118_39_fu_7732_p1;
wire   [15:0] sub_ln1118_12_fu_7736_p2;
wire   [10:0] trunc_ln708_119_fu_7742_p4;
wire   [19:0] sub_ln1118_13_fu_7756_p2;
wire   [14:0] trunc_ln708_120_fu_7762_p4;
wire   [19:0] sub_ln1118_16_fu_7779_p2;
wire   [14:0] trunc_ln708_122_fu_7785_p4;
wire  signed [13:0] tmp_20_fu_7815_p3;
wire  signed [14:0] sext_ln1118_44_fu_7808_p1;
wire  signed [14:0] sext_ln1118_46_fu_7822_p1;
wire   [14:0] sub_ln1118_18_fu_7826_p2;
wire   [9:0] trunc_ln708_124_fu_7832_p4;
wire   [18:0] shl_ln1118_10_fu_7846_p3;
wire  signed [19:0] sext_ln1118_47_fu_7853_p1;
wire   [19:0] sub_ln1118_19_fu_7857_p2;
wire   [14:0] trunc_ln708_125_fu_7862_p4;
wire   [16:0] shl_ln1118_11_fu_7876_p3;
wire  signed [17:0] sext_ln1118_49_fu_7887_p1;
wire  signed [17:0] sext_ln1118_48_fu_7883_p1;
wire   [17:0] sub_ln1118_20_fu_7891_p2;
wire   [12:0] trunc_ln708_126_fu_7897_p4;
wire   [19:0] sub_ln1118_21_fu_7911_p2;
wire   [14:0] trunc_ln708_127_fu_7917_p4;
wire   [19:0] mul_ln1118_13_fu_854_p2;
wire   [14:0] trunc_ln708_128_fu_7931_p4;
wire  signed [14:0] shl_ln1118_12_fu_7945_p3;
wire  signed [17:0] sext_ln1118_52_fu_7960_p1;
wire   [17:0] sub_ln1118_22_fu_7964_p2;
wire   [12:0] trunc_ln708_129_fu_7970_p4;
wire   [19:0] mul_ln1118_14_fu_858_p2;
wire   [14:0] trunc_ln708_130_fu_7984_p4;
wire  signed [19:0] sext_ln1118_51_fu_7956_p1;
wire   [19:0] sub_ln1118_23_fu_7998_p2;
wire   [14:0] trunc_ln708_131_fu_8004_p4;
wire  signed [12:0] sext_ln1118_43_fu_7805_p1;
wire   [12:0] sub_ln1118_24_fu_8018_p2;
wire   [7:0] trunc_ln708_132_fu_8024_p4;
wire   [19:0] mul_ln1118_15_fu_845_p2;
wire   [14:0] trunc_ln708_133_fu_8038_p4;
wire  signed [12:0] shl_ln1118_13_fu_8052_p3;
wire  signed [15:0] sext_ln1118_57_fu_8067_p1;
wire  signed [15:0] sext_ln1118_50_fu_7952_p1;
wire   [15:0] sub_ln1118_25_fu_8071_p2;
wire   [10:0] trunc_ln708_134_fu_8077_p4;
wire   [19:0] mul_ln1118_16_fu_804_p2;
wire   [14:0] trunc_ln708_135_fu_8091_p4;
wire   [19:0] sub_ln1118_26_fu_8105_p2;
wire   [14:0] trunc_ln708_136_fu_8110_p4;
wire   [17:0] shl_ln1118_14_fu_8124_p3;
wire  signed [18:0] sext_ln1118_58_fu_8131_p1;
wire  signed [18:0] sext_ln1118_55_fu_8059_p1;
wire   [18:0] add_ln1118_6_fu_8135_p2;
wire   [13:0] trunc_ln708_137_fu_8141_p4;
wire  signed [15:0] sext_ln1118_42_fu_7802_p1;
wire   [15:0] add_ln1118_7_fu_8155_p2;
wire   [10:0] trunc_ln708_138_fu_8161_p4;
wire   [18:0] mul_ln1118_17_fu_828_p2;
wire   [13:0] trunc_ln708_139_fu_8175_p4;
wire   [19:0] mul_ln1118_18_fu_878_p2;
wire   [14:0] trunc_ln708_140_fu_8189_p4;
wire  signed [19:0] sext_ln1118_56_fu_8063_p1;
wire   [19:0] sub_ln1118_27_fu_8206_p2;
wire   [14:0] trunc_ln708_142_fu_8212_p4;
wire  signed [9:0] sext_ln1118_8_fu_7232_p1;
wire   [9:0] add_ln703_fu_8226_p2;
wire  signed [10:0] sext_ln1118_9_fu_7235_p1;
wire   [10:0] add_ln703_1_fu_8236_p2;
wire  signed [12:0] sext_ln708_4_fu_7432_p1;
wire   [12:0] add_ln703_2_fu_8246_p2;
wire  signed [8:0] sext_ln708_5_fu_7436_p1;
wire   [8:0] add_ln703_3_fu_8256_p2;
wire   [8:0] add_ln703_4_fu_8266_p2;
wire   [12:0] add_ln703_5_fu_8276_p2;
wire  signed [15:0] sext_ln708_6_fu_7560_p1;
wire  signed [15:0] sext_ln708_18_fu_7842_p1;
wire   [15:0] add_ln703_6_fu_8286_p2;
wire  signed [15:0] sext_ln708_fu_7189_p1;
wire  signed [15:0] sext_ln708_19_fu_7872_p1;
wire  signed [10:0] sext_ln708_1_fu_7228_p1;
wire   [10:0] add_ln703_9_fu_8304_p2;
wire  signed [15:0] sext_ln703_14_fu_8310_p1;
wire   [15:0] add_ln703_8_fu_8298_p2;
wire  signed [15:0] sext_ln708_20_fu_7907_p1;
wire  signed [10:0] sext_ln1118_34_fu_7564_p1;
wire   [10:0] add_ln703_12_fu_8326_p2;
wire  signed [15:0] sext_ln703_15_fu_8332_p1;
wire   [15:0] add_ln703_11_fu_8320_p2;
wire  signed [15:0] sext_ln708_21_fu_7927_p1;
wire  signed [15:0] sext_ln703_fu_8232_p1;
wire   [15:0] add_ln703_14_fu_8342_p2;
wire  signed [15:0] sext_ln708_7_fu_7583_p1;
wire  signed [15:0] sext_ln708_8_fu_7597_p1;
wire  signed [15:0] sext_ln708_22_fu_7941_p1;
wire  signed [13:0] sext_ln1118_10_fu_7238_p1;
wire   [13:0] add_ln703_17_fu_8360_p2;
wire  signed [15:0] sext_ln703_16_fu_8366_p1;
wire   [15:0] add_ln703_16_fu_8354_p2;
wire  signed [15:0] sext_ln708_2_fu_7280_p1;
wire  signed [15:0] sext_ln708_9_fu_7628_p1;
wire  signed [13:0] sext_ln1118_53_fu_7980_p1;
wire   [13:0] add_ln703_20_fu_8382_p2;
wire  signed [15:0] sext_ln703_17_fu_8388_p1;
wire   [15:0] add_ln703_19_fu_8376_p2;
wire  signed [15:0] sext_ln708_23_fu_7994_p1;
wire  signed [15:0] sext_ln703_9_fu_8242_p1;
wire   [15:0] add_ln703_22_fu_8398_p2;
wire  signed [15:0] sext_ln708_10_fu_7642_p1;
wire  signed [13:0] sext_ln1118_18_fu_7326_p1;
wire   [13:0] add_ln703_25_fu_8416_p2;
wire  signed [15:0] sext_ln703_18_fu_8422_p1;
wire   [15:0] add_ln703_24_fu_8410_p2;
wire  signed [15:0] sext_ln708_11_fu_7656_p1;
wire  signed [15:0] sext_ln708_24_fu_8014_p1;
wire  signed [13:0] sext_ln1118_19_fu_7330_p1;
wire   [13:0] add_ln703_28_fu_8438_p2;
wire  signed [15:0] sext_ln703_19_fu_8444_p1;
wire   [15:0] add_ln703_27_fu_8432_p2;
wire  signed [8:0] sext_ln1118_36_fu_7660_p1;
wire  signed [8:0] sext_ln1118_54_fu_8034_p1;
wire   [8:0] add_ln703_31_fu_8460_p2;
wire  signed [15:0] sext_ln703_20_fu_8466_p1;
wire   [15:0] add_ln703_30_fu_8454_p2;
wire  signed [15:0] sext_ln708_12_fu_7673_p1;
wire  signed [15:0] sext_ln708_25_fu_8048_p1;
wire  signed [14:0] sext_ln1118_21_fu_7360_p1;
wire   [14:0] add_ln703_34_fu_8482_p2;
wire  signed [15:0] sext_ln703_21_fu_8488_p1;
wire   [15:0] add_ln703_33_fu_8476_p2;
wire  signed [15:0] sext_ln708_3_fu_7380_p1;
wire  signed [15:0] sext_ln708_26_fu_8087_p1;
wire  signed [10:0] sext_ln1118_37_fu_7677_p1;
wire   [10:0] add_ln703_37_fu_8504_p2;
wire  signed [15:0] sext_ln703_22_fu_8510_p1;
wire   [15:0] add_ln703_36_fu_8498_p2;
wire  signed [14:0] sext_ln1118_22_fu_7384_p1;
wire   [14:0] add_ln703_39_fu_8520_p2;
wire  signed [15:0] sext_ln703_23_fu_8526_p1;
wire  signed [15:0] sext_ln708_13_fu_7690_p1;
wire  signed [13:0] sext_ln1118_23_fu_7403_p1;
wire   [13:0] add_ln703_42_fu_8542_p2;
wire  signed [15:0] sext_ln703_24_fu_8548_p1;
wire   [15:0] add_ln703_41_fu_8536_p2;
wire  signed [15:0] sext_ln708_27_fu_8101_p1;
wire   [15:0] add_ln703_44_fu_8558_p2;
wire  signed [15:0] sext_ln703_10_fu_8252_p1;
wire  signed [15:0] sext_ln703_11_fu_8262_p1;
wire   [15:0] add_ln703_46_fu_8570_p2;
wire  signed [15:0] sext_ln703_12_fu_8272_p1;
wire   [15:0] add_ln703_48_fu_8582_p2;
wire  signed [15:0] sext_ln708_14_fu_7721_p1;
wire  signed [15:0] sext_ln708_28_fu_8120_p1;
wire  signed [15:0] sext_ln703_13_fu_8282_p1;
wire   [15:0] add_ln703_50_fu_8594_p2;
wire   [10:0] add_ln703_53_fu_8612_p2;
wire  signed [15:0] sext_ln703_25_fu_8618_p1;
wire   [15:0] add_ln703_52_fu_8606_p2;
wire  signed [15:0] sext_ln708_29_fu_8151_p1;
wire  signed [11:0] sext_ln1118_25_fu_7455_p1;
wire   [11:0] add_ln703_56_fu_8634_p2;
wire  signed [15:0] sext_ln703_26_fu_8640_p1;
wire   [15:0] add_ln703_55_fu_8628_p2;
wire  signed [15:0] sext_ln708_15_fu_7752_p1;
wire  signed [11:0] sext_ln1118_59_fu_8171_p1;
wire   [11:0] add_ln703_59_fu_8656_p2;
wire  signed [15:0] sext_ln703_27_fu_8662_p1;
wire   [15:0] add_ln703_58_fu_8650_p2;
wire  signed [15:0] sext_ln708_16_fu_7772_p1;
wire  signed [14:0] sext_ln1118_26_fu_7459_p1;
wire   [14:0] add_ln703_62_fu_8678_p2;
wire  signed [15:0] sext_ln703_28_fu_8684_p1;
wire   [15:0] add_ln703_61_fu_8672_p2;
wire  signed [15:0] sext_ln708_30_fu_8185_p1;
wire  signed [13:0] sext_ln1118_27_fu_7478_p1;
wire   [13:0] add_ln703_65_fu_8700_p2;
wire  signed [15:0] sext_ln703_29_fu_8706_p1;
wire   [15:0] add_ln703_64_fu_8694_p2;
wire  signed [15:0] sext_ln708_31_fu_8199_p1;
wire  signed [12:0] sext_ln1118_41_fu_7776_p1;
wire   [12:0] add_ln703_68_fu_8722_p2;
wire  signed [15:0] sext_ln703_30_fu_8728_p1;
wire   [15:0] add_ln703_67_fu_8716_p2;
wire  signed [15:0] sext_ln708_17_fu_7795_p1;
wire  signed [15:0] sext_ln708_32_fu_8203_p1;
wire   [15:0] add_ln703_71_fu_8744_p2;
wire   [15:0] add_ln703_70_fu_8738_p2;
wire   [14:0] add_ln703_74_fu_8762_p2;
wire  signed [15:0] sext_ln703_31_fu_8768_p1;
wire   [15:0] add_ln703_73_fu_8756_p2;
wire  signed [13:0] sext_ln1118_28_fu_7498_p1;
wire   [13:0] add_ln703_76_fu_8778_p2;
wire  signed [15:0] sext_ln703_32_fu_8784_p1;
wire  signed [12:0] sext_ln1116_4_fu_7799_p1;
wire   [12:0] add_ln703_79_fu_8800_p2;
wire  signed [15:0] sext_ln703_33_fu_8806_p1;
wire   [15:0] add_ln703_78_fu_8794_p2;
wire  signed [15:0] sext_ln708_33_fu_8222_p1;
wire   [15:0] add_ln703_81_fu_8816_p2;
wire  signed [8:0] sext_ln1116_3_fu_7518_p1;
wire   [8:0] add_ln703_84_fu_8834_p2;
wire  signed [15:0] sext_ln703_34_fu_8840_p1;
wire   [15:0] add_ln703_83_fu_8828_p2;
wire   [14:0] add_ln703_86_fu_8850_p2;
wire  signed [15:0] sext_ln703_35_fu_8856_p1;
wire   [15:0] add_ln703_88_fu_8866_p2;
wire   [15:0] add_ln703_7_fu_8292_p2;
wire   [20:0] tmp_data_0_V_1_fu_8878_p3;
wire   [15:0] add_ln703_10_fu_8314_p2;
wire   [20:0] tmp_data_1_V_1_fu_8891_p3;
wire   [15:0] add_ln703_13_fu_8336_p2;
wire   [20:0] tmp_data_2_V_1_fu_8904_p3;
wire   [15:0] add_ln703_15_fu_8348_p2;
wire   [20:0] tmp_data_3_V_fu_8917_p3;
wire   [15:0] add_ln703_18_fu_8370_p2;
wire   [20:0] tmp_data_4_V_fu_8930_p3;
wire   [15:0] add_ln703_21_fu_8392_p2;
wire   [20:0] tmp_data_5_V_fu_8943_p3;
wire   [15:0] add_ln703_23_fu_8404_p2;
wire   [20:0] tmp_data_6_V_fu_8956_p3;
wire   [15:0] add_ln703_26_fu_8426_p2;
wire   [20:0] tmp_data_7_V_fu_8969_p3;
wire   [15:0] add_ln703_29_fu_8448_p2;
wire   [20:0] tmp_data_8_V_fu_8982_p3;
wire   [15:0] add_ln703_32_fu_8470_p2;
wire   [20:0] tmp_data_9_V_fu_8995_p3;
wire   [15:0] add_ln703_35_fu_8492_p2;
wire   [20:0] tmp_data_10_V_fu_9008_p3;
wire   [15:0] add_ln703_38_fu_8514_p2;
wire   [20:0] tmp_data_11_V_fu_9021_p3;
wire   [15:0] add_ln703_40_fu_8530_p2;
wire   [20:0] tmp_data_12_V_fu_9034_p3;
wire   [15:0] add_ln703_43_fu_8552_p2;
wire   [20:0] tmp_data_13_V_fu_9047_p3;
wire   [15:0] add_ln703_45_fu_8564_p2;
wire   [20:0] tmp_data_14_V_fu_9060_p3;
wire   [15:0] add_ln703_47_fu_8576_p2;
wire   [20:0] tmp_data_15_V_fu_9073_p3;
wire   [15:0] add_ln703_49_fu_8588_p2;
wire   [20:0] tmp_data_16_V_fu_9086_p3;
wire   [15:0] add_ln703_51_fu_8600_p2;
wire   [20:0] tmp_data_17_V_fu_9099_p3;
wire   [15:0] add_ln703_54_fu_8622_p2;
wire   [20:0] tmp_data_18_V_fu_9112_p3;
wire   [15:0] add_ln703_57_fu_8644_p2;
wire   [20:0] tmp_data_19_V_fu_9125_p3;
wire   [15:0] add_ln703_60_fu_8666_p2;
wire   [20:0] tmp_data_20_V_fu_9138_p3;
wire   [15:0] add_ln703_63_fu_8688_p2;
wire   [20:0] tmp_data_21_V_fu_9151_p3;
wire   [15:0] add_ln703_66_fu_8710_p2;
wire   [20:0] tmp_data_22_V_fu_9164_p3;
wire   [15:0] add_ln703_69_fu_8732_p2;
wire   [20:0] tmp_data_23_V_fu_9177_p3;
wire   [15:0] add_ln703_72_fu_8750_p2;
wire   [20:0] tmp_data_24_V_fu_9190_p3;
wire   [15:0] add_ln703_75_fu_8772_p2;
wire   [20:0] tmp_data_25_V_fu_9203_p3;
wire   [15:0] add_ln703_77_fu_8788_p2;
wire   [20:0] tmp_data_26_V_fu_9216_p3;
wire   [15:0] add_ln703_80_fu_8810_p2;
wire   [20:0] tmp_data_27_V_fu_9229_p3;
wire   [15:0] add_ln703_82_fu_8822_p2;
wire   [20:0] tmp_data_28_V_fu_9242_p3;
wire   [15:0] add_ln703_85_fu_8844_p2;
wire   [20:0] tmp_data_29_V_fu_9255_p3;
wire   [15:0] add_ln703_87_fu_8860_p2;
wire   [20:0] tmp_data_30_V_fu_9268_p3;
wire   [15:0] add_ln703_89_fu_8872_p2;
wire   [20:0] tmp_data_31_V_fu_9281_p3;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_data_V_data_0_V_U_apdone_blk;
wire   [15:0] data_V_data_0_V_TDATA_int;
wire    data_V_data_0_V_TVALID_int;
reg    data_V_data_0_V_TREADY_int;
wire    regslice_both_data_V_data_0_V_U_ack_in;
wire    regslice_both_data_V_data_1_V_U_apdone_blk;
wire   [15:0] data_V_data_1_V_TDATA_int;
wire    data_V_data_1_V_TVALID_int;
reg    data_V_data_1_V_TREADY_int;
wire    regslice_both_data_V_data_1_V_U_ack_in;
wire    regslice_both_data_V_data_2_V_U_apdone_blk;
wire   [15:0] data_V_data_2_V_TDATA_int;
wire    data_V_data_2_V_TVALID_int;
reg    data_V_data_2_V_TREADY_int;
wire    regslice_both_data_V_data_2_V_U_ack_in;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

regslice_both #(
    .DataWidth( 16 ))
regslice_both_data_V_data_0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_V_data_0_V_TDATA),
    .vld_in(data_V_data_0_V_TVALID),
    .ack_in(regslice_both_data_V_data_0_V_U_ack_in),
    .data_out(data_V_data_0_V_TDATA_int),
    .vld_out(data_V_data_0_V_TVALID_int),
    .ack_out(data_V_data_0_V_TREADY_int),
    .apdone_blk(regslice_both_data_V_data_0_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_data_V_data_1_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_V_data_1_V_TDATA),
    .vld_in(data_V_data_1_V_TVALID),
    .ack_in(regslice_both_data_V_data_1_V_U_ack_in),
    .data_out(data_V_data_1_V_TDATA_int),
    .vld_out(data_V_data_1_V_TVALID_int),
    .ack_out(data_V_data_1_V_TREADY_int),
    .apdone_blk(regslice_both_data_V_data_1_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_data_V_data_2_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_V_data_2_V_TDATA),
    .vld_in(data_V_data_2_V_TVALID),
    .ack_in(regslice_both_data_V_data_2_V_U_ack_in),
    .data_out(data_V_data_2_V_TDATA_int),
    .vld_out(data_V_data_2_V_TVALID_int),
    .ack_out(data_V_data_2_V_TREADY_int),
    .apdone_blk(regslice_both_data_V_data_2_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_6920_p2 == 1'd0))) begin
        i_iw_0_reg_776 <= i_iw_fu_6926_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_iw_0_reg_776 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln89_reg_9294 <= icmp_ln89_fu_6920_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_6920_p2 == 1'd0))) begin
        sext_ln1116_2_reg_9401 <= sext_ln1116_2_fu_7138_p1;
        tmp_data_0_V_cast_reg_9303 <= data_V_data_0_V_TDATA_int;
        tmp_data_0_V_reg_9332 <= tmp_data_0_V_fu_6952_p1;
        tmp_data_1_V_reg_9322 <= tmp_data_1_V_fu_6948_p1;
        tmp_data_2_V_reg_9308 <= tmp_data_2_V_fu_6944_p1;
        trunc_ln708_101_reg_9366 <= {{data_V_data_0_V_TDATA_int[11:4]}};
        trunc_ln708_103_reg_9371 <= {{mul_ln1118_7_fu_823_p2[18:5]}};
        trunc_ln708_108_reg_9376 <= {{sub_ln1118_7_fu_7048_p2[14:5]}};
        trunc_ln708_114_reg_9381 <= {{data_V_data_1_V_TDATA_int[11:4]}};
        trunc_ln708_116_reg_9386 <= {{sub_ln1118_10_fu_7074_p2[14:5]}};
        trunc_ln708_121_reg_9391 <= {{sub_ln1118_15_fu_7106_p2[16:5]}};
        trunc_ln708_123_reg_9396 <= {{sub_ln1118_17_fu_7122_p2[16:5]}};
        trunc_ln708_141_reg_9412 <= {{mul_ln1118_19_fu_863_p2[19:5]}};
        trunc_ln708_91_reg_9345 <= {{data_V_data_0_V_TDATA_int[11:3]}};
        trunc_ln708_92_reg_9351 <= {{mul_ln1118_fu_819_p2[17:5]}};
        trunc_ln708_95_reg_9356 <= {{mul_ln1118_5_fu_862_p2[17:5]}};
        trunc_ln708_98_reg_9361 <= {{mul_ln1118_6_fu_829_p2[18:5]}};
    end
end

always @ (*) begin
    if ((icmp_ln89_fu_6920_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_6920_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_V_data_0_V_TDATA_blk_n = data_V_data_0_V_TVALID_int;
    end else begin
        data_V_data_0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((data_V_data_0_V_TVALID == 1'b1) & (regslice_both_data_V_data_0_V_U_ack_in == 1'b1))) begin
        data_V_data_0_V_TREADY = 1'b1;
    end else begin
        data_V_data_0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_6920_p2 == 1'd0))) begin
        data_V_data_0_V_TREADY_int = 1'b1;
    end else begin
        data_V_data_0_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_6920_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_V_data_1_V_TDATA_blk_n = data_V_data_1_V_TVALID_int;
    end else begin
        data_V_data_1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((data_V_data_1_V_TVALID == 1'b1) & (regslice_both_data_V_data_1_V_U_ack_in == 1'b1))) begin
        data_V_data_1_V_TREADY = 1'b1;
    end else begin
        data_V_data_1_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_6920_p2 == 1'd0))) begin
        data_V_data_1_V_TREADY_int = 1'b1;
    end else begin
        data_V_data_1_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_6920_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_V_data_2_V_TDATA_blk_n = data_V_data_2_V_TVALID_int;
    end else begin
        data_V_data_2_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((data_V_data_2_V_TVALID == 1'b1) & (regslice_both_data_V_data_2_V_U_ack_in == 1'b1))) begin
        data_V_data_2_V_TREADY = 1'b1;
    end else begin
        data_V_data_2_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_6920_p2 == 1'd0))) begin
        data_V_data_2_V_TREADY_int = 1'b1;
    end else begin
        data_V_data_2_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n;
    end else begin
        res_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_0_V_write = 1'b1;
    end else begin
        res_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_10_V_blk_n = res_V_data_10_V_full_n;
    end else begin
        res_V_data_10_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_10_V_write = 1'b1;
    end else begin
        res_V_data_10_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_11_V_blk_n = res_V_data_11_V_full_n;
    end else begin
        res_V_data_11_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_11_V_write = 1'b1;
    end else begin
        res_V_data_11_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_12_V_blk_n = res_V_data_12_V_full_n;
    end else begin
        res_V_data_12_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_12_V_write = 1'b1;
    end else begin
        res_V_data_12_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_13_V_blk_n = res_V_data_13_V_full_n;
    end else begin
        res_V_data_13_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_13_V_write = 1'b1;
    end else begin
        res_V_data_13_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_14_V_blk_n = res_V_data_14_V_full_n;
    end else begin
        res_V_data_14_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_14_V_write = 1'b1;
    end else begin
        res_V_data_14_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_15_V_blk_n = res_V_data_15_V_full_n;
    end else begin
        res_V_data_15_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_15_V_write = 1'b1;
    end else begin
        res_V_data_15_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_16_V_blk_n = res_V_data_16_V_full_n;
    end else begin
        res_V_data_16_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_16_V_write = 1'b1;
    end else begin
        res_V_data_16_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_17_V_blk_n = res_V_data_17_V_full_n;
    end else begin
        res_V_data_17_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_17_V_write = 1'b1;
    end else begin
        res_V_data_17_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_18_V_blk_n = res_V_data_18_V_full_n;
    end else begin
        res_V_data_18_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_18_V_write = 1'b1;
    end else begin
        res_V_data_18_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_19_V_blk_n = res_V_data_19_V_full_n;
    end else begin
        res_V_data_19_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_19_V_write = 1'b1;
    end else begin
        res_V_data_19_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n;
    end else begin
        res_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_1_V_write = 1'b1;
    end else begin
        res_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_20_V_blk_n = res_V_data_20_V_full_n;
    end else begin
        res_V_data_20_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_20_V_write = 1'b1;
    end else begin
        res_V_data_20_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_21_V_blk_n = res_V_data_21_V_full_n;
    end else begin
        res_V_data_21_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_21_V_write = 1'b1;
    end else begin
        res_V_data_21_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_22_V_blk_n = res_V_data_22_V_full_n;
    end else begin
        res_V_data_22_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_22_V_write = 1'b1;
    end else begin
        res_V_data_22_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_23_V_blk_n = res_V_data_23_V_full_n;
    end else begin
        res_V_data_23_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_23_V_write = 1'b1;
    end else begin
        res_V_data_23_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_24_V_blk_n = res_V_data_24_V_full_n;
    end else begin
        res_V_data_24_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_24_V_write = 1'b1;
    end else begin
        res_V_data_24_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_25_V_blk_n = res_V_data_25_V_full_n;
    end else begin
        res_V_data_25_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_25_V_write = 1'b1;
    end else begin
        res_V_data_25_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_26_V_blk_n = res_V_data_26_V_full_n;
    end else begin
        res_V_data_26_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_26_V_write = 1'b1;
    end else begin
        res_V_data_26_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_27_V_blk_n = res_V_data_27_V_full_n;
    end else begin
        res_V_data_27_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_27_V_write = 1'b1;
    end else begin
        res_V_data_27_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_28_V_blk_n = res_V_data_28_V_full_n;
    end else begin
        res_V_data_28_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_28_V_write = 1'b1;
    end else begin
        res_V_data_28_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_29_V_blk_n = res_V_data_29_V_full_n;
    end else begin
        res_V_data_29_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_29_V_write = 1'b1;
    end else begin
        res_V_data_29_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n;
    end else begin
        res_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_2_V_write = 1'b1;
    end else begin
        res_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_30_V_blk_n = res_V_data_30_V_full_n;
    end else begin
        res_V_data_30_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_30_V_write = 1'b1;
    end else begin
        res_V_data_30_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_31_V_blk_n = res_V_data_31_V_full_n;
    end else begin
        res_V_data_31_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_31_V_write = 1'b1;
    end else begin
        res_V_data_31_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n;
    end else begin
        res_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_3_V_write = 1'b1;
    end else begin
        res_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n;
    end else begin
        res_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_4_V_write = 1'b1;
    end else begin
        res_V_data_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n;
    end else begin
        res_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_5_V_write = 1'b1;
    end else begin
        res_V_data_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n;
    end else begin
        res_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_6_V_write = 1'b1;
    end else begin
        res_V_data_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n;
    end else begin
        res_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_7_V_write = 1'b1;
    end else begin
        res_V_data_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_8_V_blk_n = res_V_data_8_V_full_n;
    end else begin
        res_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_8_V_write = 1'b1;
    end else begin
        res_V_data_8_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_9_V_blk_n = res_V_data_9_V_full_n;
    end else begin
        res_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_9294 == 1'd0))) begin
        res_V_data_9_V_write = 1'b1;
    end else begin
        res_V_data_9_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_6920_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_6920_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1118_1_fu_7344_p2 = ($signed(sext_ln1118_20_fu_7340_p1) + $signed(sext_ln1118_5_fu_7200_p1));

assign add_ln1118_2_fu_7387_p2 = ($signed(sext_ln1118_15_fu_7291_p1) + $signed(sext_ln1118_6_fu_7204_p1));

assign add_ln1118_3_fu_7416_p2 = ($signed(sext_ln1118_24_fu_7412_p1) + $signed(sext_ln1118_11_fu_7248_p1));

assign add_ln1118_4_fu_7439_p2 = ($signed(sext_ln1118_17_fu_7306_p1) + $signed(sext_ln1118_12_fu_7252_p1));

assign add_ln1118_5_fu_7462_p2 = ($signed(sext_ln1118_15_fu_7291_p1) + $signed(sext_ln1118_13_fu_7256_p1));

assign add_ln1118_6_fu_8135_p2 = ($signed(sext_ln1118_58_fu_8131_p1) + $signed(sext_ln1118_55_fu_8059_p1));

assign add_ln1118_7_fu_8155_p2 = ($signed(sext_ln1118_50_fu_7952_p1) + $signed(sext_ln1118_42_fu_7802_p1));

assign add_ln1118_fu_7310_p2 = ($signed(sext_ln1118_15_fu_7291_p1) + $signed(sext_ln1118_16_fu_7302_p1));

assign add_ln703_10_fu_8314_p2 = ($signed(sext_ln703_14_fu_8310_p1) + $signed(add_ln703_8_fu_8298_p2));

assign add_ln703_11_fu_8320_p2 = ($signed(sext_ln708_fu_7189_p1) + $signed(sext_ln708_20_fu_7907_p1));

assign add_ln703_12_fu_8326_p2 = ($signed(11'd160) + $signed(sext_ln1118_34_fu_7564_p1));

assign add_ln703_13_fu_8336_p2 = ($signed(sext_ln703_15_fu_8332_p1) + $signed(add_ln703_11_fu_8320_p2));

assign add_ln703_14_fu_8342_p2 = ($signed(sext_ln708_21_fu_7927_p1) + $signed(sext_ln703_fu_8232_p1));

assign add_ln703_15_fu_8348_p2 = ($signed(add_ln703_14_fu_8342_p2) + $signed(sext_ln708_7_fu_7583_p1));

assign add_ln703_16_fu_8354_p2 = ($signed(sext_ln708_8_fu_7597_p1) + $signed(sext_ln708_22_fu_7941_p1));

assign add_ln703_17_fu_8360_p2 = ($signed(14'd16000) + $signed(sext_ln1118_10_fu_7238_p1));

assign add_ln703_18_fu_8370_p2 = ($signed(sext_ln703_16_fu_8366_p1) + $signed(add_ln703_16_fu_8354_p2));

assign add_ln703_19_fu_8376_p2 = ($signed(sext_ln708_2_fu_7280_p1) + $signed(sext_ln708_9_fu_7628_p1));

assign add_ln703_1_fu_8236_p2 = ($signed(11'd1448) + $signed(sext_ln1118_9_fu_7235_p1));

assign add_ln703_20_fu_8382_p2 = ($signed(14'd432) + $signed(sext_ln1118_53_fu_7980_p1));

assign add_ln703_21_fu_8392_p2 = ($signed(sext_ln703_17_fu_8388_p1) + $signed(add_ln703_19_fu_8376_p2));

assign add_ln703_22_fu_8398_p2 = ($signed(sext_ln708_23_fu_7994_p1) + $signed(sext_ln703_9_fu_8242_p1));

assign add_ln703_23_fu_8404_p2 = ($signed(add_ln703_22_fu_8398_p2) + $signed(sext_ln708_10_fu_7642_p1));

assign add_ln703_24_fu_8410_p2 = ($signed(sext_ln708_8_fu_7597_p1) + $signed(sext_ln708_21_fu_7927_p1));

assign add_ln703_25_fu_8416_p2 = ($signed(14'd16208) + $signed(sext_ln1118_18_fu_7326_p1));

assign add_ln703_26_fu_8426_p2 = ($signed(sext_ln703_18_fu_8422_p1) + $signed(add_ln703_24_fu_8410_p2));

assign add_ln703_27_fu_8432_p2 = ($signed(sext_ln708_11_fu_7656_p1) + $signed(sext_ln708_24_fu_8014_p1));

assign add_ln703_28_fu_8438_p2 = ($signed(14'd16096) + $signed(sext_ln1118_19_fu_7330_p1));

assign add_ln703_29_fu_8448_p2 = ($signed(sext_ln703_19_fu_8444_p1) + $signed(add_ln703_27_fu_8432_p2));

assign add_ln703_2_fu_8246_p2 = ($signed(13'd96) + $signed(sext_ln708_4_fu_7432_p1));

assign add_ln703_30_fu_8454_p2 = ($signed(16'd144) + $signed(sext_ln708_fu_7189_p1));

assign add_ln703_31_fu_8460_p2 = ($signed(sext_ln1118_36_fu_7660_p1) + $signed(sext_ln1118_54_fu_8034_p1));

assign add_ln703_32_fu_8470_p2 = ($signed(sext_ln703_20_fu_8466_p1) + $signed(add_ln703_30_fu_8454_p2));

assign add_ln703_33_fu_8476_p2 = ($signed(sext_ln708_12_fu_7673_p1) + $signed(sext_ln708_25_fu_8048_p1));

assign add_ln703_34_fu_8482_p2 = ($signed(15'd32576) + $signed(sext_ln1118_21_fu_7360_p1));

assign add_ln703_35_fu_8492_p2 = ($signed(sext_ln703_21_fu_8488_p1) + $signed(add_ln703_33_fu_8476_p2));

assign add_ln703_36_fu_8498_p2 = ($signed(sext_ln708_3_fu_7380_p1) + $signed(sext_ln708_26_fu_8087_p1));

assign add_ln703_37_fu_8504_p2 = ($signed(11'd104) + $signed(sext_ln1118_37_fu_7677_p1));

assign add_ln703_38_fu_8514_p2 = ($signed(sext_ln703_22_fu_8510_p1) + $signed(add_ln703_36_fu_8498_p2));

assign add_ln703_39_fu_8520_p2 = ($signed(15'd32520) + $signed(sext_ln1118_22_fu_7384_p1));

assign add_ln703_3_fu_8256_p2 = ($signed(9'd488) + $signed(sext_ln708_5_fu_7436_p1));

assign add_ln703_40_fu_8530_p2 = ($signed(sext_ln703_23_fu_8526_p1) + $signed(add_ln703_8_fu_8298_p2));

assign add_ln703_41_fu_8536_p2 = ($signed(sext_ln708_13_fu_7690_p1) + $signed(sext_ln708_21_fu_7927_p1));

assign add_ln703_42_fu_8542_p2 = ($signed(14'd16344) + $signed(sext_ln1118_23_fu_7403_p1));

assign add_ln703_43_fu_8552_p2 = ($signed(sext_ln703_24_fu_8548_p1) + $signed(add_ln703_41_fu_8536_p2));

assign add_ln703_44_fu_8558_p2 = ($signed(sext_ln708_6_fu_7560_p1) + $signed(sext_ln708_27_fu_8101_p1));

assign add_ln703_45_fu_8564_p2 = ($signed(add_ln703_44_fu_8558_p2) + $signed(sext_ln703_10_fu_8252_p1));

assign add_ln703_46_fu_8570_p2 = ($signed(sext_ln708_21_fu_7927_p1) + $signed(sext_ln703_11_fu_8262_p1));

assign add_ln703_47_fu_8576_p2 = ($signed(add_ln703_46_fu_8570_p2) + $signed(sext_ln708_7_fu_7583_p1));

assign add_ln703_48_fu_8582_p2 = ($signed(sext_ln708_21_fu_7927_p1) + $signed(sext_ln703_12_fu_8272_p1));

assign add_ln703_49_fu_8588_p2 = ($signed(add_ln703_48_fu_8582_p2) + $signed(sext_ln708_14_fu_7721_p1));

assign add_ln703_4_fu_8266_p2 = ($signed(9'd464) + $signed(sext_ln708_5_fu_7436_p1));

assign add_ln703_50_fu_8594_p2 = ($signed(sext_ln708_28_fu_8120_p1) + $signed(sext_ln703_13_fu_8282_p1));

assign add_ln703_51_fu_8600_p2 = ($signed(add_ln703_50_fu_8594_p2) + $signed(sext_ln708_6_fu_7560_p1));

assign add_ln703_52_fu_8606_p2 = ($signed(sext_ln708_14_fu_7721_p1) + $signed(sext_ln708_19_fu_7872_p1));

assign add_ln703_53_fu_8612_p2 = ($signed(11'd2008) + $signed(sext_ln708_1_fu_7228_p1));

assign add_ln703_54_fu_8622_p2 = ($signed(sext_ln703_25_fu_8618_p1) + $signed(add_ln703_52_fu_8606_p2));

assign add_ln703_55_fu_8628_p2 = ($signed(sext_ln708_8_fu_7597_p1) + $signed(sext_ln708_29_fu_8151_p1));

assign add_ln703_56_fu_8634_p2 = ($signed(12'd3992) + $signed(sext_ln1118_25_fu_7455_p1));

assign add_ln703_57_fu_8644_p2 = ($signed(sext_ln703_26_fu_8640_p1) + $signed(add_ln703_55_fu_8628_p2));

assign add_ln703_58_fu_8650_p2 = ($signed(sext_ln708_fu_7189_p1) + $signed(sext_ln708_15_fu_7752_p1));

assign add_ln703_59_fu_8656_p2 = ($signed(12'd200) + $signed(sext_ln1118_59_fu_8171_p1));

assign add_ln703_5_fu_8276_p2 = ($signed(13'd8008) + $signed(sext_ln1118_1_fu_7156_p1));

assign add_ln703_60_fu_8666_p2 = ($signed(sext_ln703_27_fu_8662_p1) + $signed(add_ln703_58_fu_8650_p2));

assign add_ln703_61_fu_8672_p2 = ($signed(sext_ln708_16_fu_7772_p1) + $signed(sext_ln708_19_fu_7872_p1));

assign add_ln703_62_fu_8678_p2 = ($signed(15'd32648) + $signed(sext_ln1118_26_fu_7459_p1));

assign add_ln703_63_fu_8688_p2 = ($signed(sext_ln703_28_fu_8684_p1) + $signed(add_ln703_61_fu_8672_p2));

assign add_ln703_64_fu_8694_p2 = ($signed(sext_ln708_6_fu_7560_p1) + $signed(sext_ln708_30_fu_8185_p1));

assign add_ln703_65_fu_8700_p2 = ($signed(14'd16224) + $signed(sext_ln1118_27_fu_7478_p1));

assign add_ln703_66_fu_8710_p2 = ($signed(sext_ln703_29_fu_8706_p1) + $signed(add_ln703_64_fu_8694_p2));

assign add_ln703_67_fu_8716_p2 = ($signed(sext_ln708_2_fu_7280_p1) + $signed(sext_ln708_31_fu_8199_p1));

assign add_ln703_68_fu_8722_p2 = ($signed(13'd64) + $signed(sext_ln1118_41_fu_7776_p1));

assign add_ln703_69_fu_8732_p2 = ($signed(sext_ln703_30_fu_8728_p1) + $signed(add_ln703_67_fu_8716_p2));

assign add_ln703_6_fu_8286_p2 = ($signed(sext_ln708_6_fu_7560_p1) + $signed(sext_ln708_18_fu_7842_p1));

assign add_ln703_70_fu_8738_p2 = ($signed(sext_ln708_3_fu_7380_p1) + $signed(sext_ln708_17_fu_7795_p1));

assign add_ln703_71_fu_8744_p2 = ($signed(16'd320) + $signed(sext_ln708_32_fu_8203_p1));

assign add_ln703_72_fu_8750_p2 = (add_ln703_71_fu_8744_p2 + add_ln703_70_fu_8738_p2);

assign add_ln703_73_fu_8756_p2 = ($signed(sext_ln708_6_fu_7560_p1) + $signed(sext_ln708_21_fu_7927_p1));

assign add_ln703_74_fu_8762_p2 = ($signed(15'd32712) + $signed(sext_ln1118_22_fu_7384_p1));

assign add_ln703_75_fu_8772_p2 = ($signed(sext_ln703_31_fu_8768_p1) + $signed(add_ln703_73_fu_8756_p2));

assign add_ln703_76_fu_8778_p2 = ($signed(14'd16136) + $signed(sext_ln1118_28_fu_7498_p1));

assign add_ln703_77_fu_8788_p2 = ($signed(sext_ln703_32_fu_8784_p1) + $signed(add_ln703_61_fu_8672_p2));

assign add_ln703_78_fu_8794_p2 = ($signed(sext_ln708_3_fu_7380_p1) + $signed(sext_ln708_23_fu_7994_p1));

assign add_ln703_79_fu_8800_p2 = ($signed(13'd136) + $signed(sext_ln1116_4_fu_7799_p1));

assign add_ln703_7_fu_8292_p2 = ($signed(add_ln703_6_fu_8286_p2) + $signed(sext_ln708_fu_7189_p1));

assign add_ln703_80_fu_8810_p2 = ($signed(sext_ln703_33_fu_8806_p1) + $signed(add_ln703_78_fu_8794_p2));

assign add_ln703_81_fu_8816_p2 = ($signed(sext_ln708_7_fu_7583_p1) + $signed(sext_ln708_33_fu_8222_p1));

assign add_ln703_82_fu_8822_p2 = ($signed(add_ln703_81_fu_8816_p2) + $signed(sext_ln703_10_fu_8252_p1));

assign add_ln703_83_fu_8828_p2 = ($signed(sext_ln708_6_fu_7560_p1) + $signed(sext_ln708_28_fu_8120_p1));

assign add_ln703_84_fu_8834_p2 = ($signed(9'd448) + $signed(sext_ln1116_3_fu_7518_p1));

assign add_ln703_85_fu_8844_p2 = ($signed(sext_ln703_34_fu_8840_p1) + $signed(add_ln703_83_fu_8828_p2));

assign add_ln703_86_fu_8850_p2 = ($signed(15'd32704) + $signed(sext_ln1118_22_fu_7384_p1));

assign add_ln703_87_fu_8860_p2 = ($signed(sext_ln703_35_fu_8856_p1) + $signed(add_ln703_8_fu_8298_p2));

assign add_ln703_88_fu_8866_p2 = ($signed(sext_ln708_19_fu_7872_p1) + $signed(sext_ln703_11_fu_8262_p1));

assign add_ln703_89_fu_8872_p2 = ($signed(add_ln703_88_fu_8866_p2) + $signed(sext_ln708_6_fu_7560_p1));

assign add_ln703_8_fu_8298_p2 = ($signed(sext_ln708_6_fu_7560_p1) + $signed(sext_ln708_19_fu_7872_p1));

assign add_ln703_9_fu_8304_p2 = ($signed(11'd2000) + $signed(sext_ln708_1_fu_7228_p1));

assign add_ln703_fu_8226_p2 = ($signed(10'd1000) + $signed(sext_ln1118_8_fu_7232_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((io_acc_block_signal_op465 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln89_reg_9294 == 1'd0)) | ((io_acc_block_signal_op46 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_6920_p2 == 1'd0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((io_acc_block_signal_op465 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln89_reg_9294 == 1'd0)) | ((io_acc_block_signal_op46 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_6920_p2 == 1'd0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((io_acc_block_signal_op465 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln89_reg_9294 == 1'd0)) | ((io_acc_block_signal_op46 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_6920_p2 == 1'd0)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((io_acc_block_signal_op46 == 1'b0) & (icmp_ln89_fu_6920_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((io_acc_block_signal_op465 == 1'b0) & (icmp_ln89_reg_9294 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign i_iw_fu_6926_p2 = (i_iw_0_reg_776 + 5'd1);

assign icmp_ln89_fu_6920_p2 = ((i_iw_0_reg_776 == 5'd16) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op46 = (data_V_data_2_V_TVALID_int & data_V_data_1_V_TVALID_int & data_V_data_0_V_TVALID_int);

assign io_acc_block_signal_op465 = (res_V_data_9_V_full_n & res_V_data_8_V_full_n & res_V_data_7_V_full_n & res_V_data_6_V_full_n & res_V_data_5_V_full_n & res_V_data_4_V_full_n & res_V_data_3_V_full_n & res_V_data_31_V_full_n & res_V_data_30_V_full_n & res_V_data_2_V_full_n & res_V_data_29_V_full_n & res_V_data_28_V_full_n & res_V_data_27_V_full_n & res_V_data_26_V_full_n & res_V_data_25_V_full_n & res_V_data_24_V_full_n & res_V_data_23_V_full_n & res_V_data_22_V_full_n & res_V_data_21_V_full_n & res_V_data_20_V_full_n & res_V_data_1_V_full_n & res_V_data_19_V_full_n & res_V_data_18_V_full_n & res_V_data_17_V_full_n & res_V_data_16_V_full_n & res_V_data_15_V_full_n & res_V_data_14_V_full_n & res_V_data_13_V_full_n & res_V_data_12_V_full_n & res_V_data_11_V_full_n & res_V_data_10_V_full_n & res_V_data_0_V_full_n);

assign mul_ln1118_10_fu_809_p1 = sext_ln1116_1_fu_7522_p1;

assign mul_ln1118_10_fu_809_p2 = ($signed(20'd1048453) * $signed(mul_ln1118_10_fu_809_p1));

assign mul_ln1118_11_fu_807_p1 = sext_ln1116_1_fu_7522_p1;

assign mul_ln1118_11_fu_807_p2 = ($signed(20'd1048467) * $signed(mul_ln1118_11_fu_807_p1));

assign mul_ln1118_12_fu_832_p1 = sext_ln1116_1_fu_7522_p1;

assign mul_ln1118_12_fu_832_p2 = ($signed(20'd1048486) * $signed(mul_ln1118_12_fu_832_p1));

assign mul_ln1118_13_fu_854_p1 = sext_ln1116_2_reg_9401;

assign mul_ln1118_13_fu_854_p2 = ($signed({{1'b0}, {20'd123}}) * $signed(mul_ln1118_13_fu_854_p1));

assign mul_ln1118_14_fu_858_p1 = sext_ln1116_2_reg_9401;

assign mul_ln1118_14_fu_858_p2 = ($signed({{1'b0}, {20'd114}}) * $signed(mul_ln1118_14_fu_858_p1));

assign mul_ln1118_15_fu_845_p1 = sext_ln1116_2_reg_9401;

assign mul_ln1118_15_fu_845_p2 = ($signed({{1'b0}, {20'd93}}) * $signed(mul_ln1118_15_fu_845_p1));

assign mul_ln1118_16_fu_804_p1 = sext_ln1116_2_reg_9401;

assign mul_ln1118_16_fu_804_p2 = ($signed(20'd1048453) * $signed(mul_ln1118_16_fu_804_p1));

assign mul_ln1118_17_fu_828_p1 = tmp_data_2_V_reg_9308;

assign mul_ln1118_17_fu_828_p2 = ($signed(19'd524241) * $signed(mul_ln1118_17_fu_828_p1));

assign mul_ln1118_18_fu_878_p1 = sext_ln1116_2_reg_9401;

assign mul_ln1118_18_fu_878_p2 = ($signed({{1'b0}, {20'd98}}) * $signed(mul_ln1118_18_fu_878_p1));

assign mul_ln1118_19_fu_863_p1 = tmp_data_2_V_fu_6944_p1;

assign mul_ln1118_19_fu_863_p2 = ($signed(20'd1048462) * $signed(mul_ln1118_19_fu_863_p1));

assign mul_ln1118_5_fu_862_p1 = sext_ln1118_fu_6956_p1;

assign mul_ln1118_5_fu_862_p2 = ($signed({{1'b0}, {18'd25}}) * $signed(mul_ln1118_5_fu_862_p1));

assign mul_ln1118_6_fu_829_p1 = sext_ln1118_3_fu_6962_p1;

assign mul_ln1118_6_fu_829_p2 = ($signed({{1'b0}, {19'd37}}) * $signed(mul_ln1118_6_fu_829_p1));

assign mul_ln1118_7_fu_823_p1 = sext_ln1118_3_fu_6962_p1;

assign mul_ln1118_7_fu_823_p2 = ($signed({{1'b0}, {19'd35}}) * $signed(mul_ln1118_7_fu_823_p1));

assign mul_ln1118_8_fu_801_p1 = sext_ln1116_1_fu_7522_p1;

assign mul_ln1118_8_fu_801_p2 = ($signed(20'd1048451) * $signed(mul_ln1118_8_fu_801_p1));

assign mul_ln1118_9_fu_792_p1 = sext_ln1116_1_fu_7522_p1;

assign mul_ln1118_9_fu_792_p2 = ($signed({{1'b0}, {20'd115}}) * $signed(mul_ln1118_9_fu_792_p1));

assign mul_ln1118_fu_819_p1 = sext_ln1118_fu_6956_p1;

assign mul_ln1118_fu_819_p2 = ($signed({{1'b0}, {18'd19}}) * $signed(mul_ln1118_fu_819_p1));

assign res_V_data_0_V_din = $signed(tmp_data_0_V_1_fu_8878_p3);

assign res_V_data_10_V_din = $signed(tmp_data_10_V_fu_9008_p3);

assign res_V_data_11_V_din = $signed(tmp_data_11_V_fu_9021_p3);

assign res_V_data_12_V_din = $signed(tmp_data_12_V_fu_9034_p3);

assign res_V_data_13_V_din = $signed(tmp_data_13_V_fu_9047_p3);

assign res_V_data_14_V_din = $signed(tmp_data_14_V_fu_9060_p3);

assign res_V_data_15_V_din = $signed(tmp_data_15_V_fu_9073_p3);

assign res_V_data_16_V_din = $signed(tmp_data_16_V_fu_9086_p3);

assign res_V_data_17_V_din = $signed(tmp_data_17_V_fu_9099_p3);

assign res_V_data_18_V_din = $signed(tmp_data_18_V_fu_9112_p3);

assign res_V_data_19_V_din = $signed(tmp_data_19_V_fu_9125_p3);

assign res_V_data_1_V_din = $signed(tmp_data_1_V_1_fu_8891_p3);

assign res_V_data_20_V_din = $signed(tmp_data_20_V_fu_9138_p3);

assign res_V_data_21_V_din = $signed(tmp_data_21_V_fu_9151_p3);

assign res_V_data_22_V_din = $signed(tmp_data_22_V_fu_9164_p3);

assign res_V_data_23_V_din = $signed(tmp_data_23_V_fu_9177_p3);

assign res_V_data_24_V_din = $signed(tmp_data_24_V_fu_9190_p3);

assign res_V_data_25_V_din = $signed(tmp_data_25_V_fu_9203_p3);

assign res_V_data_26_V_din = $signed(tmp_data_26_V_fu_9216_p3);

assign res_V_data_27_V_din = $signed(tmp_data_27_V_fu_9229_p3);

assign res_V_data_28_V_din = $signed(tmp_data_28_V_fu_9242_p3);

assign res_V_data_29_V_din = $signed(tmp_data_29_V_fu_9255_p3);

assign res_V_data_2_V_din = $signed(tmp_data_2_V_1_fu_8904_p3);

assign res_V_data_30_V_din = $signed(tmp_data_30_V_fu_9268_p3);

assign res_V_data_31_V_din = $signed(tmp_data_31_V_fu_9281_p3);

assign res_V_data_3_V_din = $signed(tmp_data_3_V_fu_8917_p3);

assign res_V_data_4_V_din = $signed(tmp_data_4_V_fu_8930_p3);

assign res_V_data_5_V_din = $signed(tmp_data_5_V_fu_8943_p3);

assign res_V_data_6_V_din = $signed(tmp_data_6_V_fu_8956_p3);

assign res_V_data_7_V_din = $signed(tmp_data_7_V_fu_8969_p3);

assign res_V_data_8_V_din = $signed(tmp_data_8_V_fu_8982_p3);

assign res_V_data_9_V_din = $signed(tmp_data_9_V_fu_8995_p3);

assign sext_ln1116_1_fu_7522_p1 = tmp_data_1_V_reg_9322;

assign sext_ln1116_2_fu_7138_p1 = tmp_data_2_V_fu_6944_p1;

assign sext_ln1116_3_fu_7518_p1 = $signed(trunc_ln708_106_fu_7508_p4);

assign sext_ln1116_4_fu_7799_p1 = $signed(trunc_ln708_123_reg_9396);

assign sext_ln1116_fu_7153_p1 = tmp_data_0_V_reg_9332;

assign sext_ln1118_10_fu_7238_p1 = $signed(trunc_ln708_92_reg_9351);

assign sext_ln1118_11_fu_7248_p1 = shl_ln1118_1_fu_7241_p3;

assign sext_ln1118_12_fu_7252_p1 = shl_ln1118_1_fu_7241_p3;

assign sext_ln1118_13_fu_7256_p1 = shl_ln1118_1_fu_7241_p3;

assign sext_ln1118_14_fu_7260_p1 = shl_ln1118_1_fu_7241_p3;

assign sext_ln1118_15_fu_7291_p1 = $signed(shl_ln1118_2_fu_7284_p3);

assign sext_ln1118_16_fu_7302_p1 = shl_ln1118_3_fu_7295_p3;

assign sext_ln1118_17_fu_7306_p1 = shl_ln1118_3_fu_7295_p3;

assign sext_ln1118_18_fu_7326_p1 = $signed(trunc_ln708_94_fu_7316_p4);

assign sext_ln1118_19_fu_7330_p1 = $signed(trunc_ln708_95_reg_9356);

assign sext_ln1118_1_fu_7156_p1 = tmp_data_0_V_reg_9332;

assign sext_ln1118_20_fu_7340_p1 = $signed(shl_ln1118_4_fu_7333_p3);

assign sext_ln1118_21_fu_7360_p1 = $signed(trunc_ln708_96_fu_7350_p4);

assign sext_ln1118_22_fu_7384_p1 = $signed(trunc_ln708_98_reg_9361);

assign sext_ln1118_23_fu_7403_p1 = $signed(trunc_ln708_99_fu_7393_p4);

assign sext_ln1118_24_fu_7412_p1 = $signed(shl_ln1118_fu_7407_p2);

assign sext_ln1118_25_fu_7455_p1 = $signed(trunc_ln708_102_fu_7445_p4);

assign sext_ln1118_26_fu_7459_p1 = $signed(trunc_ln708_103_reg_9371);

assign sext_ln1118_27_fu_7478_p1 = $signed(trunc_ln708_104_fu_7468_p4);

assign sext_ln1118_28_fu_7498_p1 = $signed(trunc_ln708_105_fu_7488_p4);

assign sext_ln1118_29_fu_7530_p1 = tmp_data_1_V_reg_9322;

assign sext_ln1118_2_fu_7159_p1 = tmp_data_0_V_reg_9332;

assign sext_ln1118_30_fu_7028_p1 = tmp_data_1_V_fu_6948_p1;

assign sext_ln1118_31_fu_7540_p1 = $signed(shl_ln1118_6_fu_7533_p3);

assign sext_ln1118_32_fu_7040_p1 = shl_ln1118_7_fu_7032_p3;

assign sext_ln1118_33_fu_7044_p1 = shl_ln1118_7_fu_7032_p3;

assign sext_ln1118_34_fu_7564_p1 = $signed(trunc_ln708_108_reg_9376);

assign sext_ln1118_35_fu_7608_p1 = $signed(shl_ln1118_8_fu_7601_p3);

assign sext_ln1118_36_fu_7660_p1 = $signed(trunc_ln708_114_reg_9381);

assign sext_ln1118_37_fu_7677_p1 = $signed(trunc_ln708_116_reg_9386);

assign sext_ln1118_38_fu_7701_p1 = $signed(shl_ln1118_9_fu_7694_p3);

assign sext_ln1118_39_fu_7732_p1 = $signed(tmp_17_fu_7725_p3);

assign sext_ln1118_3_fu_6962_p1 = tmp_data_0_V_fu_6952_p1;

assign sext_ln1118_40_fu_7096_p1 = $signed(shl_ln1118_5_fu_7090_p2);

assign sext_ln1118_41_fu_7776_p1 = $signed(trunc_ln708_121_reg_9391);

assign sext_ln1118_42_fu_7802_p1 = tmp_data_2_V_reg_9308;

assign sext_ln1118_43_fu_7805_p1 = tmp_data_2_V_reg_9308;

assign sext_ln1118_44_fu_7808_p1 = tmp_data_2_V_reg_9308;

assign sext_ln1118_46_fu_7822_p1 = tmp_20_fu_7815_p3;

assign sext_ln1118_47_fu_7853_p1 = $signed(shl_ln1118_10_fu_7846_p3);

assign sext_ln1118_48_fu_7883_p1 = $signed(shl_ln1118_11_fu_7876_p3);

assign sext_ln1118_49_fu_7887_p1 = tmp_20_fu_7815_p3;

assign sext_ln1118_4_fu_7169_p1 = $signed(shl_ln_fu_7162_p3);

assign sext_ln1118_50_fu_7952_p1 = shl_ln1118_12_fu_7945_p3;

assign sext_ln1118_51_fu_7956_p1 = shl_ln1118_12_fu_7945_p3;

assign sext_ln1118_52_fu_7960_p1 = shl_ln1118_12_fu_7945_p3;

assign sext_ln1118_53_fu_7980_p1 = $signed(trunc_ln708_129_fu_7970_p4);

assign sext_ln1118_54_fu_8034_p1 = $signed(trunc_ln708_132_fu_8024_p4);

assign sext_ln1118_55_fu_8059_p1 = shl_ln1118_13_fu_8052_p3;

assign sext_ln1118_56_fu_8063_p1 = shl_ln1118_13_fu_8052_p3;

assign sext_ln1118_57_fu_8067_p1 = shl_ln1118_13_fu_8052_p3;

assign sext_ln1118_58_fu_8131_p1 = $signed(shl_ln1118_14_fu_8124_p3);

assign sext_ln1118_59_fu_8171_p1 = $signed(trunc_ln708_138_fu_8161_p4);

assign sext_ln1118_5_fu_7200_p1 = shl_ln1118_s_fu_7193_p3;

assign sext_ln1118_6_fu_7204_p1 = shl_ln1118_s_fu_7193_p3;

assign sext_ln1118_7_fu_7208_p1 = shl_ln1118_s_fu_7193_p3;

assign sext_ln1118_8_fu_7232_p1 = trunc_ln708_91_reg_9345;

assign sext_ln1118_9_fu_7235_p1 = trunc_ln708_91_reg_9345;

assign sext_ln1118_fu_6956_p1 = tmp_data_0_V_fu_6952_p1;

assign sext_ln703_10_fu_8252_p1 = $signed(add_ln703_2_fu_8246_p2);

assign sext_ln703_11_fu_8262_p1 = $signed(add_ln703_3_fu_8256_p2);

assign sext_ln703_12_fu_8272_p1 = $signed(add_ln703_4_fu_8266_p2);

assign sext_ln703_13_fu_8282_p1 = $signed(add_ln703_5_fu_8276_p2);

assign sext_ln703_14_fu_8310_p1 = $signed(add_ln703_9_fu_8304_p2);

assign sext_ln703_15_fu_8332_p1 = $signed(add_ln703_12_fu_8326_p2);

assign sext_ln703_16_fu_8366_p1 = $signed(add_ln703_17_fu_8360_p2);

assign sext_ln703_17_fu_8388_p1 = $signed(add_ln703_20_fu_8382_p2);

assign sext_ln703_18_fu_8422_p1 = $signed(add_ln703_25_fu_8416_p2);

assign sext_ln703_19_fu_8444_p1 = $signed(add_ln703_28_fu_8438_p2);

assign sext_ln703_20_fu_8466_p1 = $signed(add_ln703_31_fu_8460_p2);

assign sext_ln703_21_fu_8488_p1 = $signed(add_ln703_34_fu_8482_p2);

assign sext_ln703_22_fu_8510_p1 = $signed(add_ln703_37_fu_8504_p2);

assign sext_ln703_23_fu_8526_p1 = $signed(add_ln703_39_fu_8520_p2);

assign sext_ln703_24_fu_8548_p1 = $signed(add_ln703_42_fu_8542_p2);

assign sext_ln703_25_fu_8618_p1 = $signed(add_ln703_53_fu_8612_p2);

assign sext_ln703_26_fu_8640_p1 = $signed(add_ln703_56_fu_8634_p2);

assign sext_ln703_27_fu_8662_p1 = $signed(add_ln703_59_fu_8656_p2);

assign sext_ln703_28_fu_8684_p1 = $signed(add_ln703_62_fu_8678_p2);

assign sext_ln703_29_fu_8706_p1 = $signed(add_ln703_65_fu_8700_p2);

assign sext_ln703_30_fu_8728_p1 = $signed(add_ln703_68_fu_8722_p2);

assign sext_ln703_31_fu_8768_p1 = $signed(add_ln703_74_fu_8762_p2);

assign sext_ln703_32_fu_8784_p1 = $signed(add_ln703_76_fu_8778_p2);

assign sext_ln703_33_fu_8806_p1 = $signed(add_ln703_79_fu_8800_p2);

assign sext_ln703_34_fu_8840_p1 = $signed(add_ln703_84_fu_8834_p2);

assign sext_ln703_35_fu_8856_p1 = $signed(add_ln703_86_fu_8850_p2);

assign sext_ln703_9_fu_8242_p1 = $signed(add_ln703_1_fu_8236_p2);

assign sext_ln703_fu_8232_p1 = $signed(add_ln703_fu_8226_p2);

assign sext_ln708_10_fu_7642_p1 = $signed(trunc_ln708_112_fu_7632_p4);

assign sext_ln708_11_fu_7656_p1 = $signed(trunc_ln708_113_fu_7646_p4);

assign sext_ln708_12_fu_7673_p1 = $signed(trunc_ln708_115_fu_7663_p4);

assign sext_ln708_13_fu_7690_p1 = $signed(trunc_ln708_117_fu_7680_p4);

assign sext_ln708_14_fu_7721_p1 = $signed(trunc_ln708_118_fu_7711_p4);

assign sext_ln708_15_fu_7752_p1 = $signed(trunc_ln708_119_fu_7742_p4);

assign sext_ln708_16_fu_7772_p1 = $signed(trunc_ln708_120_fu_7762_p4);

assign sext_ln708_17_fu_7795_p1 = $signed(trunc_ln708_122_fu_7785_p4);

assign sext_ln708_18_fu_7842_p1 = $signed(trunc_ln708_124_fu_7832_p4);

assign sext_ln708_19_fu_7872_p1 = $signed(trunc_ln708_125_fu_7862_p4);

assign sext_ln708_1_fu_7228_p1 = $signed(trunc_ln708_s_fu_7218_p4);

assign sext_ln708_20_fu_7907_p1 = $signed(trunc_ln708_126_fu_7897_p4);

assign sext_ln708_21_fu_7927_p1 = $signed(trunc_ln708_127_fu_7917_p4);

assign sext_ln708_22_fu_7941_p1 = $signed(trunc_ln708_128_fu_7931_p4);

assign sext_ln708_23_fu_7994_p1 = $signed(trunc_ln708_130_fu_7984_p4);

assign sext_ln708_24_fu_8014_p1 = $signed(trunc_ln708_131_fu_8004_p4);

assign sext_ln708_25_fu_8048_p1 = $signed(trunc_ln708_133_fu_8038_p4);

assign sext_ln708_26_fu_8087_p1 = $signed(trunc_ln708_134_fu_8077_p4);

assign sext_ln708_27_fu_8101_p1 = $signed(trunc_ln708_135_fu_8091_p4);

assign sext_ln708_28_fu_8120_p1 = $signed(trunc_ln708_136_fu_8110_p4);

assign sext_ln708_29_fu_8151_p1 = $signed(trunc_ln708_137_fu_8141_p4);

assign sext_ln708_2_fu_7280_p1 = $signed(trunc_ln708_93_fu_7270_p4);

assign sext_ln708_30_fu_8185_p1 = $signed(trunc_ln708_139_fu_8175_p4);

assign sext_ln708_31_fu_8199_p1 = $signed(trunc_ln708_140_fu_8189_p4);

assign sext_ln708_32_fu_8203_p1 = $signed(trunc_ln708_141_reg_9412);

assign sext_ln708_33_fu_8222_p1 = $signed(trunc_ln708_142_fu_8212_p4);

assign sext_ln708_3_fu_7380_p1 = $signed(trunc_ln708_97_fu_7370_p4);

assign sext_ln708_4_fu_7432_p1 = $signed(trunc_ln708_100_fu_7422_p4);

assign sext_ln708_5_fu_7436_p1 = $signed(trunc_ln708_101_reg_9366);

assign sext_ln708_6_fu_7560_p1 = $signed(trunc_ln708_107_fu_7550_p4);

assign sext_ln708_7_fu_7583_p1 = $signed(trunc_ln708_109_fu_7573_p4);

assign sext_ln708_8_fu_7597_p1 = $signed(trunc_ln708_110_fu_7587_p4);

assign sext_ln708_9_fu_7628_p1 = $signed(trunc_ln708_111_fu_7618_p4);

assign sext_ln708_fu_7189_p1 = $signed(trunc_ln_fu_7179_p4);

assign shl_ln1118_10_fu_7846_p3 = {{tmp_data_2_V_reg_9308}, {7'd0}};

assign shl_ln1118_11_fu_7876_p3 = {{tmp_data_2_V_reg_9308}, {5'd0}};

assign shl_ln1118_12_fu_7945_p3 = {{tmp_data_2_V_reg_9308}, {3'd0}};

assign shl_ln1118_13_fu_8052_p3 = {{tmp_data_2_V_reg_9308}, {1'd0}};

assign shl_ln1118_14_fu_8124_p3 = {{tmp_data_2_V_reg_9308}, {6'd0}};

assign shl_ln1118_1_fu_7241_p3 = {{tmp_data_0_V_reg_9332}, {1'd0}};

assign shl_ln1118_2_fu_7284_p3 = {{tmp_data_0_V_reg_9332}, {5'd0}};

assign shl_ln1118_3_fu_7295_p3 = {{tmp_data_0_V_reg_9332}, {3'd0}};

assign shl_ln1118_4_fu_7333_p3 = {{tmp_data_0_V_reg_9332}, {6'd0}};

assign shl_ln1118_5_fu_7090_p2 = data_V_data_1_V_TDATA_int << 16'd4;

assign shl_ln1118_6_fu_7533_p3 = {{tmp_data_1_V_reg_9322}, {7'd0}};

assign shl_ln1118_7_fu_7032_p3 = {{tmp_data_1_V_fu_6948_p1}, {2'd0}};

assign shl_ln1118_8_fu_7601_p3 = {{tmp_data_1_V_reg_9322}, {6'd0}};

assign shl_ln1118_9_fu_7694_p3 = {{tmp_data_1_V_reg_9322}, {1'd0}};

assign shl_ln1118_fu_7407_p2 = tmp_data_0_V_cast_reg_9303 << 16'd4;

assign shl_ln1118_s_fu_7193_p3 = {{tmp_data_0_V_reg_9332}, {2'd0}};

assign shl_ln_fu_7162_p3 = {{tmp_data_0_V_reg_9332}, {7'd0}};

assign start_out = real_start;

assign sub_ln1118_10_fu_7074_p2 = ($signed(sub_ln1118_7_fu_7048_p2) - $signed(sext_ln1118_30_fu_7028_p1));

assign sub_ln1118_11_fu_7705_p2 = ($signed(sext_ln1118_38_fu_7701_p1) - $signed(sext_ln1118_31_fu_7540_p1));

assign sub_ln1118_12_fu_7736_p2 = ($signed(sext_ln1118_29_fu_7530_p1) - $signed(sext_ln1118_39_fu_7732_p1));

assign sub_ln1118_13_fu_7756_p2 = ($signed(20'd0) - $signed(sext_ln1118_31_fu_7540_p1));

assign sub_ln1118_14_fu_7100_p2 = ($signed(17'd0) - $signed(sext_ln1118_40_fu_7096_p1));

assign sub_ln1118_15_fu_7106_p2 = ($signed(sub_ln1118_14_fu_7100_p2) - $signed(sext_ln1118_32_fu_7040_p1));

assign sub_ln1118_16_fu_7779_p2 = ($signed(sext_ln1118_31_fu_7540_p1) - $signed(sext_ln1118_38_fu_7701_p1));

assign sub_ln1118_17_fu_7122_p2 = ($signed(sext_ln1118_32_fu_7040_p1) - $signed(sext_ln1118_40_fu_7096_p1));

assign sub_ln1118_18_fu_7826_p2 = ($signed(sext_ln1118_44_fu_7808_p1) - $signed(sext_ln1118_46_fu_7822_p1));

assign sub_ln1118_19_fu_7857_p2 = ($signed(sext_ln1118_47_fu_7853_p1) - $signed(sext_ln1116_2_reg_9401));

assign sub_ln1118_1_fu_7212_p2 = ($signed(sext_ln1118_7_fu_7208_p1) - $signed(sext_ln1118_2_fu_7159_p1));

assign sub_ln1118_20_fu_7891_p2 = ($signed(sext_ln1118_49_fu_7887_p1) - $signed(sext_ln1118_48_fu_7883_p1));

assign sub_ln1118_21_fu_7911_p2 = ($signed(20'd0) - $signed(sext_ln1118_47_fu_7853_p1));

assign sub_ln1118_22_fu_7964_p2 = ($signed(sext_ln1118_48_fu_7883_p1) - $signed(sext_ln1118_52_fu_7960_p1));

assign sub_ln1118_23_fu_7998_p2 = ($signed(sext_ln1118_51_fu_7956_p1) - $signed(sext_ln1118_47_fu_7853_p1));

assign sub_ln1118_24_fu_8018_p2 = ($signed(13'd0) - $signed(sext_ln1118_43_fu_7805_p1));

assign sub_ln1118_25_fu_8071_p2 = ($signed(sext_ln1118_57_fu_8067_p1) - $signed(sext_ln1118_50_fu_7952_p1));

assign sub_ln1118_26_fu_8105_p2 = ($signed(sext_ln1116_2_reg_9401) - $signed(sext_ln1118_47_fu_7853_p1));

assign sub_ln1118_27_fu_8206_p2 = ($signed(sext_ln1118_47_fu_7853_p1) - $signed(sext_ln1118_56_fu_8063_p1));

assign sub_ln1118_2_fu_7264_p2 = ($signed(sext_ln1118_14_fu_7260_p1) - $signed(sext_ln1118_4_fu_7169_p1));

assign sub_ln1118_3_fu_7364_p2 = ($signed(sext_ln1116_fu_7153_p1) - $signed(sext_ln1118_4_fu_7169_p1));

assign sub_ln1118_4_fu_7482_p2 = ($signed(sext_ln1118_15_fu_7291_p1) - $signed(sext_ln1118_13_fu_7256_p1));

assign sub_ln1118_5_fu_7502_p2 = ($signed(13'd0) - $signed(sext_ln1118_1_fu_7156_p1));

assign sub_ln1118_6_fu_7544_p2 = ($signed(sext_ln1118_31_fu_7540_p1) - $signed(sext_ln1116_1_fu_7522_p1));

assign sub_ln1118_7_fu_7048_p2 = ($signed(15'd0) - $signed(sext_ln1118_33_fu_7044_p1));

assign sub_ln1118_8_fu_7567_p2 = ($signed(sext_ln1116_1_fu_7522_p1) - $signed(sext_ln1118_31_fu_7540_p1));

assign sub_ln1118_9_fu_7612_p2 = ($signed(19'd0) - $signed(sext_ln1118_35_fu_7608_p1));

assign sub_ln1118_fu_7173_p2 = ($signed(20'd0) - $signed(sext_ln1118_4_fu_7169_p1));

assign tmp_17_fu_7725_p3 = {{tmp_data_1_V_reg_9322}, {3'd0}};

assign tmp_20_fu_7815_p3 = {{tmp_data_2_V_reg_9308}, {2'd0}};

assign tmp_data_0_V_1_fu_8878_p3 = {{add_ln703_7_fu_8292_p2}, {5'd0}};

assign tmp_data_0_V_fu_6952_p1 = data_V_data_0_V_TDATA_int[11:0];

assign tmp_data_10_V_fu_9008_p3 = {{add_ln703_35_fu_8492_p2}, {5'd0}};

assign tmp_data_11_V_fu_9021_p3 = {{add_ln703_38_fu_8514_p2}, {5'd0}};

assign tmp_data_12_V_fu_9034_p3 = {{add_ln703_40_fu_8530_p2}, {5'd0}};

assign tmp_data_13_V_fu_9047_p3 = {{add_ln703_43_fu_8552_p2}, {5'd0}};

assign tmp_data_14_V_fu_9060_p3 = {{add_ln703_45_fu_8564_p2}, {5'd0}};

assign tmp_data_15_V_fu_9073_p3 = {{add_ln703_47_fu_8576_p2}, {5'd0}};

assign tmp_data_16_V_fu_9086_p3 = {{add_ln703_49_fu_8588_p2}, {5'd0}};

assign tmp_data_17_V_fu_9099_p3 = {{add_ln703_51_fu_8600_p2}, {5'd0}};

assign tmp_data_18_V_fu_9112_p3 = {{add_ln703_54_fu_8622_p2}, {5'd0}};

assign tmp_data_19_V_fu_9125_p3 = {{add_ln703_57_fu_8644_p2}, {5'd0}};

assign tmp_data_1_V_1_fu_8891_p3 = {{add_ln703_10_fu_8314_p2}, {5'd0}};

assign tmp_data_1_V_fu_6948_p1 = data_V_data_1_V_TDATA_int[11:0];

assign tmp_data_20_V_fu_9138_p3 = {{add_ln703_60_fu_8666_p2}, {5'd0}};

assign tmp_data_21_V_fu_9151_p3 = {{add_ln703_63_fu_8688_p2}, {5'd0}};

assign tmp_data_22_V_fu_9164_p3 = {{add_ln703_66_fu_8710_p2}, {5'd0}};

assign tmp_data_23_V_fu_9177_p3 = {{add_ln703_69_fu_8732_p2}, {5'd0}};

assign tmp_data_24_V_fu_9190_p3 = {{add_ln703_72_fu_8750_p2}, {5'd0}};

assign tmp_data_25_V_fu_9203_p3 = {{add_ln703_75_fu_8772_p2}, {5'd0}};

assign tmp_data_26_V_fu_9216_p3 = {{add_ln703_77_fu_8788_p2}, {5'd0}};

assign tmp_data_27_V_fu_9229_p3 = {{add_ln703_80_fu_8810_p2}, {5'd0}};

assign tmp_data_28_V_fu_9242_p3 = {{add_ln703_82_fu_8822_p2}, {5'd0}};

assign tmp_data_29_V_fu_9255_p3 = {{add_ln703_85_fu_8844_p2}, {5'd0}};

assign tmp_data_2_V_1_fu_8904_p3 = {{add_ln703_13_fu_8336_p2}, {5'd0}};

assign tmp_data_2_V_fu_6944_p1 = data_V_data_2_V_TDATA_int[11:0];

assign tmp_data_30_V_fu_9268_p3 = {{add_ln703_87_fu_8860_p2}, {5'd0}};

assign tmp_data_31_V_fu_9281_p3 = {{add_ln703_89_fu_8872_p2}, {5'd0}};

assign tmp_data_3_V_fu_8917_p3 = {{add_ln703_15_fu_8348_p2}, {5'd0}};

assign tmp_data_4_V_fu_8930_p3 = {{add_ln703_18_fu_8370_p2}, {5'd0}};

assign tmp_data_5_V_fu_8943_p3 = {{add_ln703_21_fu_8392_p2}, {5'd0}};

assign tmp_data_6_V_fu_8956_p3 = {{add_ln703_23_fu_8404_p2}, {5'd0}};

assign tmp_data_7_V_fu_8969_p3 = {{add_ln703_26_fu_8426_p2}, {5'd0}};

assign tmp_data_8_V_fu_8982_p3 = {{add_ln703_29_fu_8448_p2}, {5'd0}};

assign tmp_data_9_V_fu_8995_p3 = {{add_ln703_32_fu_8470_p2}, {5'd0}};

assign trunc_ln708_100_fu_7422_p4 = {{add_ln1118_3_fu_7416_p2[16:5]}};

assign trunc_ln708_102_fu_7445_p4 = {{add_ln1118_4_fu_7439_p2[15:5]}};

assign trunc_ln708_104_fu_7468_p4 = {{add_ln1118_5_fu_7462_p2[17:5]}};

assign trunc_ln708_105_fu_7488_p4 = {{sub_ln1118_4_fu_7482_p2[17:5]}};

assign trunc_ln708_106_fu_7508_p4 = {{sub_ln1118_5_fu_7502_p2[12:5]}};

assign trunc_ln708_107_fu_7550_p4 = {{sub_ln1118_6_fu_7544_p2[19:5]}};

assign trunc_ln708_109_fu_7573_p4 = {{sub_ln1118_8_fu_7567_p2[19:5]}};

assign trunc_ln708_110_fu_7587_p4 = {{mul_ln1118_8_fu_801_p2[19:5]}};

assign trunc_ln708_111_fu_7618_p4 = {{sub_ln1118_9_fu_7612_p2[18:5]}};

assign trunc_ln708_112_fu_7632_p4 = {{mul_ln1118_9_fu_792_p2[19:5]}};

assign trunc_ln708_113_fu_7646_p4 = {{mul_ln1118_10_fu_809_p2[19:5]}};

assign trunc_ln708_115_fu_7663_p4 = {{mul_ln1118_11_fu_807_p2[19:5]}};

assign trunc_ln708_117_fu_7680_p4 = {{mul_ln1118_12_fu_832_p2[19:5]}};

assign trunc_ln708_118_fu_7711_p4 = {{sub_ln1118_11_fu_7705_p2[19:5]}};

assign trunc_ln708_119_fu_7742_p4 = {{sub_ln1118_12_fu_7736_p2[15:5]}};

assign trunc_ln708_120_fu_7762_p4 = {{sub_ln1118_13_fu_7756_p2[19:5]}};

assign trunc_ln708_122_fu_7785_p4 = {{sub_ln1118_16_fu_7779_p2[19:5]}};

assign trunc_ln708_124_fu_7832_p4 = {{sub_ln1118_18_fu_7826_p2[14:5]}};

assign trunc_ln708_125_fu_7862_p4 = {{sub_ln1118_19_fu_7857_p2[19:5]}};

assign trunc_ln708_126_fu_7897_p4 = {{sub_ln1118_20_fu_7891_p2[17:5]}};

assign trunc_ln708_127_fu_7917_p4 = {{sub_ln1118_21_fu_7911_p2[19:5]}};

assign trunc_ln708_128_fu_7931_p4 = {{mul_ln1118_13_fu_854_p2[19:5]}};

assign trunc_ln708_129_fu_7970_p4 = {{sub_ln1118_22_fu_7964_p2[17:5]}};

assign trunc_ln708_130_fu_7984_p4 = {{mul_ln1118_14_fu_858_p2[19:5]}};

assign trunc_ln708_131_fu_8004_p4 = {{sub_ln1118_23_fu_7998_p2[19:5]}};

assign trunc_ln708_132_fu_8024_p4 = {{sub_ln1118_24_fu_8018_p2[12:5]}};

assign trunc_ln708_133_fu_8038_p4 = {{mul_ln1118_15_fu_845_p2[19:5]}};

assign trunc_ln708_134_fu_8077_p4 = {{sub_ln1118_25_fu_8071_p2[15:5]}};

assign trunc_ln708_135_fu_8091_p4 = {{mul_ln1118_16_fu_804_p2[19:5]}};

assign trunc_ln708_136_fu_8110_p4 = {{sub_ln1118_26_fu_8105_p2[19:5]}};

assign trunc_ln708_137_fu_8141_p4 = {{add_ln1118_6_fu_8135_p2[18:5]}};

assign trunc_ln708_138_fu_8161_p4 = {{add_ln1118_7_fu_8155_p2[15:5]}};

assign trunc_ln708_139_fu_8175_p4 = {{mul_ln1118_17_fu_828_p2[18:5]}};

assign trunc_ln708_140_fu_8189_p4 = {{mul_ln1118_18_fu_878_p2[19:5]}};

assign trunc_ln708_142_fu_8212_p4 = {{sub_ln1118_27_fu_8206_p2[19:5]}};

assign trunc_ln708_93_fu_7270_p4 = {{sub_ln1118_2_fu_7264_p2[19:5]}};

assign trunc_ln708_94_fu_7316_p4 = {{add_ln1118_fu_7310_p2[17:5]}};

assign trunc_ln708_96_fu_7350_p4 = {{add_ln1118_1_fu_7344_p2[18:5]}};

assign trunc_ln708_97_fu_7370_p4 = {{sub_ln1118_3_fu_7364_p2[19:5]}};

assign trunc_ln708_99_fu_7393_p4 = {{add_ln1118_2_fu_7387_p2[17:5]}};

assign trunc_ln708_s_fu_7218_p4 = {{sub_ln1118_1_fu_7212_p2[14:5]}};

assign trunc_ln_fu_7179_p4 = {{sub_ln1118_fu_7173_p2[19:5]}};

endmodule //pointwise_conv_1d_cl_array_array_ap_fixed_23_8_5_3_0_32u_config19_s
